### ISSUE TITLE
[Question] 请问有方法或者配置项可以屏蔽掉基类的api吗

### ISSUE THREAD

**Issue by pistoolster** [tangcent/easy-yapi#1032]
项目的controller都集成自一个基类的controller，这个controller class里面的api有办法可以屏蔽掉只导出我覆写的api吗

**Comment by tangcent** [comment]
配一条[ignore](http://easyyapi.com/setting/rules/ignore.html):
```properties
ignore=groovy:it.defineClass().name()=='xxx.xxx.xxx'
```

不确定值怎么配可以试试打日志看看，像这样:
``````properties
ignore=groovy:```
  logger.info("it: " + it + ", defineClass:" + it.defineClass().name())
```
``````

**Comment by pistoolster** [comment]
感谢回复！添加之后报错了，但是其实上传成功了哈
```
[ERROR]	error eval script:it.defineClass().name()=='xxx.xxx.xxx.ApiController'
[TRACE]	javax.script.ScriptException: javax.script.ScriptException: groovy.lang.MissingMethodException: No signature of method: com.itangcent.idea.plugin.rule.ScriptRuleParser$ScriptPsiClassContext.defineClass() is applicable for argument types: () values: []
Possible solutions: defineCode(), getClass()
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:158)
	at com.itangcent.idea.plugin.rule.ScriptRuleParser.eval(ScriptRuleParser.kt:97)
	at com.itangcent.idea.plugin.rule.ScriptRuleParser.access$eval(ScriptRuleParser.kt:34)
	at com.itangcent.idea.plugin.rule.ScriptRuleParser$parseBooleanRule$1.invoke(ScriptRuleParser.kt:65)
	at com.itangcent.idea.plugin.rule.ScriptRuleParser$parseBooleanRule$1.invoke(ScriptRuleParser.kt:64)
	at com.itangcent.intellij.config.rule.BooleanRule$Companion$of$2.compute(BooleanRule.kt:36)
	at com.itangcent.intellij.config.rule.BooleanRule$Companion$of$2.compute(BooleanRule.kt:34)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer$RuleChainImpl.compute(DefaultRuleComputer.kt:73)
	at com.itangcent.intellij.config.rule.BooleanRuleMode$ANY$compute$1.invoke(RuleMode.kt:52)
	at com.itangcent.intellij.config.rule.BooleanRuleMode$ANY$compute$1.invoke(RuleMode.kt:52)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at com.itangcent.intellij.config.rule.BooleanRuleMode$ANY.compute(RuleMode.kt:95)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer.doComputer(DefaultRuleComputer.kt:54)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer$computer$1.invoke(DefaultRuleComputer.kt:30)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer$computer$1.invoke(DefaultRuleComputer.kt:28)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry.computerListener(RuleComputeListenerRegistry.kt:34)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry.access$computerListener(RuleComputeListenerRegistry.kt:10)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry$computerListener$1.invoke(RuleComputeListenerRegistry.kt:31)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry$computerListener$1.invoke(RuleComputeListenerRegistry.kt:30)
	at com.itangcent.idea.utils.ContextualPsiClassHelper$InnerComputeListener.computer(ContextualPsiClassHelper.kt:260)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry.computerListener(RuleComputeListenerRegistry.kt:30)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry.computer(RuleComputeListenerRegistry.kt:24)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer.computer(DefaultRuleComputer.kt:28)
	at com.itangcent.intellij.config.rule.RuleComputer$DefaultImpls.computer(RuleComputer.kt:12)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer.computer(DefaultRuleComputer.kt:8)
	at com.itangcent.idea.plugin.api.export.core.RequestClassExporter.shouldIgnore(RequestClassExporter.kt:174)
	at com.itangcent.idea.plugin.api.export.core.RequestClassExporter.doExport(RequestClassExporter.kt:126)
	at com.itangcent.idea.plugin.api.export.core.RequestClassExporter.export(RequestClassExporter.kt:113)
	at com.itangcent.idea.plugin.api.export.core.CompositeClassExporter.export(CompositeClassExporter.kt:25)
	at com.itangcent.idea.plugin.api.ClassApiExporterHelper$export$3.invoke(ClassApiExporterHelper.kt:243)
	at com.itangcent.idea.plugin.api.ClassApiExporterHelper$export$3.invoke(ClassApiExporterHelper.kt:242)
	at com.itangcent.intellij.extend.ActionContextKitKt.withBoundary(ActionContextKit.kt:61)
	at com.itangcent.idea.plugin.api.ClassApiExporterHelper.export(ClassApiExporterHelper.kt:242)
	at com.itangcent.idea.plugin.api.export.yapi.YapiApiExporter.doExport(YapiApiExporter.kt:34)
	at com.itangcent.idea.plugin.api.export.yapi.YapiApiExporter.export(YapiApiExporter.kt:28)
	at com.itangcent.idea.plugin.actions.YapiExportAction.actionPerformed(YapiExportAction.kt:57)
	at com.itangcent.intellij.actions.KotlinAnAction$actionPerformed$2.invoke(KotlinAnAction.kt:49)
	at com.itangcent.intellij.actions.KotlinAnAction$actionPerformed$2.invoke(KotlinAnAction.kt:47)
	at com.itangcent.intellij.context.ActionContext.runAsync$lambda$9(ActionContext.kt:216)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: javax.script.ScriptException: groovy.lang.MissingMethodException: No signature of method: com.itangcent.idea.plugin.rule.ScriptRuleParser$ScriptPsiClassContext.defineClass() is applicable for argument types: () values: []
Possible solutions: defineCode(), getClass()
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:320)
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:155)
	... 43 more
Caused by: groovy.lang.MissingMethodException: No signature of method: com.itangcent.idea.plugin.rule.ScriptRuleParser$ScriptPsiClassContext.defineClass() is applicable for argument types: () values: []
Possible solutions: defineCode(), getClass()
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:70)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:46)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
	at Script436.run(Script436.groovy:1)
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:317)
	... 44 more
```

**Comment by tangcent** [comment]
加一下`it.contextType()=="method"`:
`ignore=groovy:it.contextType()=="method"&&it.defineClass().name()=='xxx.xxx.xxx'`
ignore这条规则有点特殊，同时对class和method都生效。

**Comment by pistoolster** [comment]
完美解决，感谢大佬！
