### ISSUE TITLE
[Bug] java.io.FileNotFoundException: \ (系统找不到指定的路径。)

### ISSUE THREAD

**Issue by minglea** [tangcent/easy-yapi#1106]
我正常配置之后第一次可以成功之后会报这个错误

run easy-yapi
[TRACE]	No config be found
[DEBUG]	use recommend config
[ERROR]	failed load remote config
[TRACE]	java.io.FileNotFoundException: \ (系统找不到指定的路径。)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at com.itangcent.intellij.config.resource.FileResource.getInputStream(FileResource.kt:42)
	at com.itangcent.intellij.config.resource.Resource.getBytes(Resource.kt:21)
	at com.itangcent.idea.plugin.settings.helper.RemoteConfigSettingsHelper.refreshConfig(RemoteConfigSettingsHelper.kt:49)
	at com.itangcent.idea.plugin.settings.helper.RemoteConfigSettingsHelper.loadConfig(RemoteConfigSettingsHelper.kt:44)
	at com.itangcent.idea.plugin.settings.helper.RemoteConfigSettingsHelper$remoteConfigContent$3.invoke(RemoteConfigSettingsHelper.kt:40)
	at com.itangcent.idea.plugin.settings.helper.RemoteConfigSettingsHelper$remoteConfigContent$3.invoke(RemoteConfigSettingsHelper.kt:40)
	at kotlin.text.StringsKt__AppendableKt.appendElement(Appendable.kt:85)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:3490)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt:3507)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:3506)
	at com.itangcent.idea.plugin.settings.helper.RemoteConfigSettingsHelper.remoteConfigContent(RemoteConfigSettingsHelper.kt:40)
	at com.itangcent.idea.plugin.config.RecommendConfigReader.tryLoadRemote(RecommendConfigReader.kt:189)
	at com.itangcent.idea.plugin.config.RecommendConfigReader.initDelegateAndRecommend(RecommendConfigReader.kt:135)
	at com.itangcent.idea.plugin.config.RecommendConfigReader.checkStatus(RecommendConfigReader.kt:79)
	at com.itangcent.idea.plugin.config.RecommendConfigReader.first(RecommendConfigReader.kt:53)
	at com.itangcent.idea.plugin.settings.helper.YapiSettingsHelper.getServer(YapiSettingsHelper.kt:54)
	at com.itangcent.idea.plugin.api.export.yapi.YapiApiExporter.export(YapiApiExporter.kt:26)
	at com.itangcent.idea.plugin.actions.YapiExportAction.actionPerformed(YapiExportAction.kt:57)
	at com.itangcent.intellij.actions.KotlinAnAction$actionPerformed$2.invoke(KotlinAnAction.kt:49)
	at com.itangcent.intellij.actions.KotlinAnAction$actionPerformed$2.invoke(KotlinAnAction.kt:47)
	at com.itangcent.intellij.context.ActionContext.runAsync$lambda$9(ActionContext.kt:215)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

[INFO]	Start export api...
[TRACE]	No config be found
[ERROR]	error resolve property [check_groups] because [check_groups] has more than one value!
[INFO]	To resolve this error,please check configs
Or change the resolveMultiType from default `ERROR` to [`FIRST`,`LAST`,`LONGEST`,`SHORTEST`]
For Instance:###set resolveMulti = FIRST
[ERROR]	error resolve property [check_groups] because [check_groups] has more than one value!
[ERROR]	unable to resolve property:check_groups
[INFO]	To ignore this error,surround with:
###set ignoreUnresolved = true
###set ignoreUnresolved = false
[ERROR]	error resolve property [check_groups] because [check_groups] has more than one value!
[ERROR]	error resolve property [check_groups] because [check_groups] has more than one value!
[ERROR]	unable to resolve property:check_groups
[ERROR]	error resolve property [check_groups] because [check_groups] has more than one value!
[ERROR]	error resolve property [check_groups] because [check_groups] has more than one value!
[ERROR]	unable to resolve property:check_groups
[DEBUG]	use recommend config
[ERROR]	failed load remote config
[TRACE]	java.io.FileNotFoundException: \ (系统找不到指定的路�
进程已结束，退出代码为 0

**Comment by tangcent** [comment]
1.  清理一下<kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd> > <kbd>Remote</kbd> 中无效的地址
2. 清理一下缓存: <kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd> > <kbd>Cache</kbd>

**Comment by minglea** [comment]
缓存已经清理过一次了,第一个这个无效地址我不知道我的对不对跟同事是一样的,他可以使用

**Comment by minglea** [comment]
[ERROR]	error resolve property [check_groups] because [check_groups] has more than one value!
[ERROR]	error resolve property [check_groups] because [check_groups] has more than one value!
[ERROR]	unable to resolve property:check_groups
[ERROR]	error resolve property [check_groups] because [check_groups] has more than one value!
[ERROR]	error resolve property [check_groups] because [check_groups] has more than one value!
[ERROR]	unable to resolve property:check_groups
[DEBUG]	use recommend config
[ERROR]	failed load remote config
