### ISSUE TITLE
[Bug] java.io.FileNotFoundException:频繁遇到，且不一样场景

### ISSUE THREAD

**Issue by zzskanyun** [tangcent/easy-yapi#1114]
为了能识别代码里的swagger注解我添加了对应的config，但是推接口信息的时候一直报这个错，过了半天，clear cache之后好了。
但是我的同事也遇到了这个报错，同时整个运行会卡在[INFO]	search api from: 这个地方，另外一个同事不卡，但是也有这个报错，
这是版本的bug问题吗？
[TRACE] No config be found
[DEBUG] use recommend config
[ERROR] failed load remote config
[TRACE] java.io.FileNotFoundException: \ (系统找不到指定的路径。)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.(FileInputStream.java:157)
at com.itangcent.intellij.config.resource.FileResource.getInputStream(FileResource.kt:42)
at com.itangcent.intellij.config.resource.Resource.getBytes(Resource.kt:21)
at com.itangcent.idea.plugin.settings.helper.RemoteConfigSettingsHelper.refreshConfig(RemoteConfigSettingsHelper.kt:49)
at com.itangcent.idea.plugin.settings.helper.RemoteConfigSettingsHelper.loadConfig(RemoteConfigSettingsHelper.kt:44)
at com.itangcent.idea.plugin.settings.helper.RemoteConfigSettingsHelper$remoteConfigContent$3.invoke(RemoteConfigSettingsHelper.kt:40)
at com.itangcent.idea.plugin.settings.helper.RemoteConfigSettingsHelper$remoteConfigContent$3.invoke(RemoteConfigSettingsHelper.kt:40)
at kotlin.text.StringsKt__AppendableKt.appendElement(Appendable.kt:85)
at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:3490)
at kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt:3507)
at kotlin.collections.CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:3506)
at com.itangcent.idea.plugin.settings.helper.RemoteConfigSettingsHelper.remoteConfigContent(RemoteConfigSettingsHelper.kt:40)
at com.itangcent.idea.plugin.config.RecommendConfigReader.tryLoadRemote(RecommendConfigReader.kt:189)
at

**Comment by zzskanyun** [comment]
我自己的也是过了半天清了缓存之后自己好了，但是同事的清缓存也不起作用

**Comment by tangcent** [comment]
这个issue也说有这个问题，https://github.com/tangcent/easy-yapi/issues/1106
但很奇怪我没有遇到过，你使用的windows吗?
你的配了哪些url?

能不能看看这里的日志? Logs of IDEA: <br>
   The easiest way to find the product log file is the Help menu, the item name would depend on the IDE version and OS:- Show Log in Explorer
   - Show Log in Finder
   - Show Log in Konqueror/Nautilus
   - Reveal Log in Explorer
   - Reveal Log in Finder/Finder/Nautilus

**Comment by zzskanyun** [comment]
我和我的同事都是MAC，INTEL和M3芯片都有
现在没办法复现了，我们都已经好了，可以提供一下操作路径：
第一次clear cache，不报错，控制台打印的有[DEBUG]    load remote config，
但是还是没有识别swagger注解的内容，
第二次clear cache，再次推送就好了。。。
总结就是多试几次多clear几次，不清楚到底是哪里卡住了

再次感谢作者的贡献，这个插件确实好用

**Comment by zzskanyun** [comment]
就是需要多重复清理几次缓存，看样子

**Comment by tangcent** [comment]
> 但是还是没有识别swagger注解的内容，

现在还是无法识别swagger注解吗?

**Comment by zzskanyun** [comment]
> > 但是还是没有识别swagger注解的内容，
> 
> 现在还是无法识别swagger注解吗?

可能我没表达清楚，第一次清理缓存没识别，继续多清理几次就好了，
现在是可以识别的~

**Comment by tangcent** [comment]
哈哈，那就好。不过因为我自己是不用swagger的，所以那些规则可能不全，有机会的话你可以补充一些。

**Comment by zzskanyun** [comment]
> 哈哈，那就好。不过因为我自己是不用swagger的，所以那些规则可能不全，有机会的话你可以补充一些。

我之前也是用的doc注释，现在强制需要用swagger注解，现在还不熟悉，等我熟悉熟悉，哈哈
