### ISSUE TITLE
[Question] 源代码无修改本地执行./plugin-script/package_plugin.sh报错

### ISSUE THREAD

**Issue by jingqingyun** [tangcent/easy-yapi#1159]
**报错信息**

Problems found loading plugins:
  The Android Design Tools (id=com.android.tools.design, path=~/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2023.1.3/4e0a4eba55b0959c8406c9be8c38a4937fc99bd1/ideaIC-2023.1.3/plugins/design-tools) plugin Plugin 'Android Design Tools' cannot be loaded because it depends on plugin 'Android' which failed to load
  The Android (id=org.jetbrains.android, path=~/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2023.1.3/4e0a4eba55b0959c8406c9be8c38a4937fc99bd1/ideaIC-2023.1.3/plugins/android) plugin Requires plugin 'org.intellij.groovy' to be enabled
  The Gradle-Maven (id=org.jetbrains.plugins.gradle.maven, path=~/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2023.1.3/4e0a4eba55b0959c8406c9be8c38a4937fc99bd1/ideaIC-2023.1.3/plugins/gradle-java-maven) plugin Requires plugin 'org.intellij.groovy' to be enabled
java.lang.Throwable: Problems found loading plugins:
  The Android Design Tools (id=com.android.tools.design, path=~/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2023.1.3/4e0a4eba55b0959c8406c9be8c38a4937fc99bd1/ideaIC-2023.1.3/plugins/design-tools) plugin Plugin 'Android Design Tools' cannot be loaded because it depends on plugin 'Android' which failed to load
  The Android (id=org.jetbrains.android, path=~/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2023.1.3/4e0a4eba55b0959c8406c9be8c38a4937fc99bd1/ideaIC-2023.1.3/plugins/android) plugin Requires plugin 'org.intellij.groovy' to be enabled
  The Gradle-Maven (id=org.jetbrains.plugins.gradle.maven, path=~/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2023.1.3/4e0a4eba55b0959c8406c9be8c38a4937fc99bd1/ideaIC-2023.1.3/plugins/gradle-java-maven) plugin Requires plugin 'org.intellij.groovy' to be enabled
        at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
        at com.intellij.ide.plugins.PluginManagerCore.preparePluginErrors(PluginManagerCore.java:469)
        at com.intellij.ide.plugins.PluginManagerCore.initializePlugins(PluginManagerCore.java:841)
        at com.intellij.ide.plugins.PluginManagerCore.initializeAndSetPlugins(PluginManagerCore.java:1064)
        at com.intellij.ide.plugins.PluginDescriptorLoader$scheduleLoading$pluginSetDeferred$1.invokeSuspend(PluginDescriptorLoader.kt:397)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**环境**
JDK: 17.0.7; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
OS: Mac OS X 14.4
CPU: Apple M3 Pro
IDE: IntelliJ IDEA 2024.1.4 (Community Edition) Build #IC-241.18034.62, built on June 21, 2024

**Comment by tangcent** [comment]
为什么你这里显示'Android Design Tools'加载失败, easy-yapi里并没有用到这个。我在想有没有可能你尝试编译其他插件，也用到了`/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2023.1.3/4e0a4eba55b0959c8406c9be8c38a4937fc99bd1/ideaIC-2023.1.3`,  可以尝试清理一下?

**Comment by tangcent** [comment]
如果网络没问题的话，就把`/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2023.1.3/4e0a4eba55b0959c8406c9be8c38a4937fc99bd1/ideaIC-2023.1.3`整个删掉，重新下载试试吧
