### ISSUE TITLE
[Bug] 打开 yapi dashboard 稳定输出报错

### ISSUE THREAD

**Issue by immadolf** [tangcent/easy-yapi#1168]
报错日志如下：

run easy-yapi
[ERROR]	failed to load config: 
[INFO]	load token:xxxxxxxxxxxx
[ERROR]	failed to load config: 
[ERROR]	failed to load config: 
[ERROR]	error to cache api info
[ERROR]	error to cache api info
[ERROR]	error to cache api info
[ERROR]	error to cache api info
[ERROR]	failed to load config: 
[ERROR]	failed to load config: 
[ERROR]	failed to load config: 
[ERROR]	failed to load config: 
[ERROR]	failed to load config: 
[ERROR]	failed to load config: 
[ERROR]	failed to load config: 
[ERROR]	failed to load config: 
[ERROR]	error in Async
[ERROR]	error in Async

Process finished with exit code 0

**Comment by immadolf** [comment]
@tangcent 我补充了，麻烦看看
```txt
run easy-yapi
[TRACE]	found config file:/xxxxxx
[ERROR]	failed to load config: 
[INFO]	load token:xxxxxx
[ERROR]	failed to load config: 
[ERROR]	failed to load config: 
[INFO]	search api from: xxx.xxx.morning.read.api.manager.ScriptController
[ERROR]	failed to load config: 
[ERROR]	failed to load config: 
[ERROR]	failed to load config: 
[ERROR]	failed to load config: 
[ERROR]	error to cache api info
[ERROR]	error to cache api info
[TRACE]	java.lang.NullPointerException: null cannot be cast to non-null type kotlin.collections.List<kotlin.Function1<com.itangcent.intellij.config.rule.RuleContext, T of com.itangcent.intellij.config.rule.DefaultRuleLookUp.lookUp?>{ com.itangcent.intellij.config.rule.RuleKt.Rule<T of com.itangcent.intellij.config.rule.DefaultRuleLookUp.lookUp> }>
	at com.itangcent.intellij.config.rule.DefaultRuleLookUp.lookUp(DefaultRuleLookUp.kt:41)
	at com.itangcent.intellij.config.rule.RuleLookUpKt.lookUp(RuleLookUp.kt:12)
	at com.itangcent.intellij.config.rule.DefaultRuleComputerKt.lookUp(DefaultRuleComputer.kt:59)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer.doComputer(DefaultRuleComputer.kt:43)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer$computer$1.invoke(DefaultRuleComputer.kt:30)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer$computer$1.invoke(DefaultRuleComputer.kt:28)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry.computerListener(RuleComputeListenerRegistry.kt:34)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry.access$computerListener(RuleComputeListenerRegistry.kt:10)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry$computerListener$1.invoke(RuleComputeListenerRegistry.kt:31)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry$computerListener$1.invoke(RuleComputeListenerRegistry.kt:30)
	at com.itangcent.idea.utils.ContextualPsiClassHelper$InnerComputeListener.computer(ContextualPsiClassHelper.kt:284)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry.computerListener(RuleComputeListenerRegistry.kt:30)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry.computer(RuleComputeListenerRegistry.kt:24)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer.computer(DefaultRuleComputer.kt:28)
	at com.itangcent.intellij.config.rule.RuleComputer$DefaultImpls.computer(RuleComputer.kt:12)
	at com.itangcent.intellij.[TRACE]	java.lang.NullPointerException: null cannot be cast to non-null type kotlin.collections.List<kotlin.Function1<com.itangcent.intellij.config.rule.RuleContext, T of com.itangcent.intellij.config.rule.DefaultRuleLookUp.lookUp?>{ com.itangcent.intellij.config.rule.RuleKt.Rule<T of com.itangcent.intellij.config.rule.DefaultRuleLookUp.lookUp> }>
	at com.itangcent.intellij.config.rule.DefaultRuleLookUp.lookUp(DefaultRuleLookUp.kt:41)
	at com.itangcent.intellij.config.rule.RuleLookUpKt.lookUp(RuleLookUp.kt:12)
	at com.itangcent.intellij.config.rule.DefaultRuleComputerKt.lookUp(DefaultRuleComputer.kt:59)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer.doComputer(DefaultRuleComputer.kt:43)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer$computer$1.invoke(DefaultRuleComputer.kt:30)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer$computer$1.invoke(DefaultRuleComputer.kt:28)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry.computerListener(RuleComputeListenerRegistry.kt:34)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry.access$computerListener(RuleComputeListenerRegistry.kt:10)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry$computerListener$1.invoke(RuleComputeListenerRegistry.kt:31)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry$computerListener$1.invoke(RuleComputeListenerRegistry.kt:30)
	at com.itangcent.idea.utils.ContextualPsiClassHelper$InnerComputeListener.computer(ContextualPsiClassHelper.kt:284)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry.computerListener(RuleComputeListenerRegistry.kt:30)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry.computer(RuleComputeListenerRegistry.kt:24)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer.computer(DefaultRuleComputer.kt:28)
	at com.itangcent.intellij.config.rule.RuleComputer$DefaultImpls.computer(RuleComputer.kt:12)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer.computer(DefaultRuleComputer.kt:8)
	at com.itangcent.idea.plugin.api.export.spring.SpringRequestClassExporter.hasApi(SpringRequestClassExporter.kt:55)
	at com.itangcent.idea.plugin.api.export.core.RequestClassExporter.doExport(RequestClassExporter.kt:123)
	at com.itangcent.idea.plugin.api.export.core.RequestClassExporter.export(RequestClassExporter.kt:113)
	at com.itangcent.idea.plugin.api.export.core.CompositeClassExporter.export(CompositeClassExporter.kt:25)
	at com.itangcent.idea.plugin.api.cache.CachedRequestClassExporter$export$1$2.invoke(CachedRequestClassExporter.kt:90)
	at com.itangcent.idea.plugin.api.cache.CachedRequestClassExporter$export$1$2.invoke(CachedRequestClassExporter.kt:89)
	at com.itangcent.intellij.extend.ActionContextKitKt.withBoundary(ActionContextKit.kt:61)
	at com.itangcent.idea.plugin.api.cache.CachedRequestClassExporter$export$1.invoke(CachedRequestClassExporter.kt:89)
	at com.itangcent.idea.plugin.api.cache.CachedRequestClassExporter$export$1.invoke(CachedRequestClassExporter.kt:63)
	at com.itangcent.intellij.context.ActionContext.runAsync$lambda$9(ActionContext.kt:215)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

config.rule.DefaultRuleComputer.computer(DefaultRuleComputer.kt:8)
	at com.itangcent.idea.plugin.api.export.spring.SpringRequestClassExporter.hasApi(SpringRequestClassExporter.kt:55)
	at com.itangcent.idea.plugin.api.export.core.RequestClassExporter.doExport(RequestClassExporter.kt:123)
	at com.itangcent.idea.plugin.api.export.core.RequestClassExporter.export(RequestClassExporter.kt:113)
	at com.itangcent.idea.plugin.api.export.core.CompositeClassExporter.export(CompositeClassExporter.kt:25)
	at com.itangcent.idea.plugin.api.cache.CachedRequestClassExporter$export$1$2.invoke(CachedRequestClassExporter.kt:90)
	at com.itangcent.idea.plugin.api.cache.CachedRequestClassExporter$export$1$2.invoke(CachedRequestClassExporter.kt:89)
	at com.itangcent.intellij.extend.ActionContextKitKt.withBoundary(ActionContextKit.kt:61)
	at com.itangcent.idea.plugin.api.cache.CachedRequestClassExporter$export$1.invoke(CachedRequestClassExporter.kt:89)
	at com.itangcent.idea.plugin.api.cache.CachedRequestClassExporter$export$1.invoke(CachedRequestClassExporter.kt:63)
	at com.itangcent.intellij.context.ActionContext.runAsync$lambda$9(ActionContext.kt:215)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

[ERROR]	failed to load config: 
[ERROR]	failed to load config: 
[ERROR]	error in Async
[ERROR]	error in Async
[TRACE]	java.lang.NullPointerException: null cannot be cast to non-null type kotlin.collections.List<kotlin.Function1<com.itangcent.intellij.config.rule.RuleContext, T of com.itangcent.intellij.config.rule.DefaultRuleLookUp.lookUp?>{ com.itangcent.intellij.config.rule.RuleKt.Rule<T of com.itangcent.intellij.config.rule.DefaultRuleLookUp.lookUp> }>
	at com.itangcent.intellij.config.rule.DefaultRuleLookUp.lookUp(DefaultRuleLookUp.kt:41)
	at com.itangcent.intellij.config.rule.RuleLookUpKt.lookUp(RuleLookUp.kt:12)
	at com.itangcent.intellij.config.rule.DefaultRuleComputerKt.lookUp(DefaultRuleComputer.kt:59)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer.doComputer(DefaultRuleComputer.kt:43)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer$computer$1.invoke(DefaultRuleComputer.kt:30)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer$computer$1.invoke(DefaultRuleComputer.kt:28)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry.computerListener(RuleComputeListenerRegistry.kt:34)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry.access$computerListener(RuleComputeListenerRegistry.kt:10)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry$computerListener$1.invoke(RuleComputeListenerRegistry.kt:31)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry$computerListener$1.invoke(RuleComputeListenerRegistry.kt:30)
	at com.itangcent.idea.utils.ContextualPsiClassHelper$InnerComputeListener.computer(ContextualPsiClassHelper.kt:284)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry.computerListener(RuleComputeListenerRegistry.kt:30)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry.computer(RuleComputeListenerRegistry.kt:24)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer.computer(DefaultRuleComputer.kt:28)
	at com.itangcent.intellij.config.rule.RuleComputer$DefaultImpls.computer(RuleComputer.kt:12)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer.computer(DefaultRuleComputer.kt:8)
	at com.itangcent.idea.plugin.api.export.spring.SpringRequestClassExporter.hasApi(SpringRequestClassExporter.kt:55)
	at com.itangcent.idea.plugin.api.export.core.RequestClassExporter.doExport(RequestClassExporter.kt:123)
	at com.itangcent.idea.plugin.api.export.core.RequestClassExporter.export(RequestClassExporter.kt:113)
	at com.itangcent.idea.plugin.api.export.core.CompositeClassExporter.export(CompositeClassExporter.kt:25)
	at com.itangcent.idea.plugin.api.cache.CachedRequestClassExporter.export(CachedRequestClassExporter.kt:56)
	at com.itangcent.idea.plugin.dialog.AbstractApiDashboardDialog$loadApiInClass$1$1.invoke(AbstractApiDashboardDialog.kt:314)
	at com.itangcent.idea.plugin.dialog.AbstractApiDashboardDialog$loadApiInClass$1$1.invoke(AbstractApiDashboardDialog.kt:313)
	at com.itangcent.intellij.extend.ActionContextKitKt.withBoundary(ActionContextKit.kt:61)
	at com.itangcent.idea.plugin.dialog.AbstractApiDashboardDialog$loadApiInClass$1.invoke(AbstractApiDashboardDialog.kt:313)
	at com.itangcent.idea.plugin.dialog.AbstractApiDashboardDialog$loadApiInClass$1.invoke(AbstractApiDashboardDialog.kt:311)
	at com.itangcent.intellij.context.ActionContext.runAsync$lambda$9(ActionContext.kt:215)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

[TRACE]	java.lang.NullPointerException: null cannot be cast to non-null type kotlin.collections.List<kotlin.Function1<com.itangcent.intellij.config.rule.RuleContext, T of com.itangcent.intellij.config.rule.DefaultRuleLookUp.lookUp?>{ com.itangcent.intellij.config.rule.RuleKt.Rule<T of com.itangcent.intellij.config.rule.DefaultRuleLookUp.lookUp> }>
	at com.itangcent.intellij.config.rule.DefaultRuleLookUp.lookUp(DefaultRuleLookUp.kt:41)
	at com.itangcent.intellij.config.rule.RuleLookUpKt.lookUp(RuleLookUp.kt:12)
	at com.itangcent.intellij.config.rule.DefaultRuleComputerKt.lookUp(DefaultRuleComputer.kt:59)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer.doComputer(DefaultRuleComputer.kt:43)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer$computer$1.invoke(DefaultRuleComputer.kt:30)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer$computer$1.invoke(DefaultRuleComputer.kt:28)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry.computerListener(RuleComputeListenerRegistry.kt:34)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry.access$computerListener(RuleComputeListenerRegistry.kt:10)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry$computerListener$1.invoke(RuleComputeListenerRegistry.kt:31)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry$computerListener$1.invoke(RuleComputeListenerRegistry.kt:30)
	at com.itangcent.idea.utils.ContextualPsiClassHelper$InnerComputeListener.computer(ContextualPsiClassHelper.kt:284)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry.computerListener(RuleComputeListenerRegistry.kt:30)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry.computer(RuleComputeListenerRegistry.kt:24)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer.computer(DefaultRuleComputer.kt:28)
	at com.itangcent.intellij.config.rule.RuleComputer$DefaultImpls.computer(RuleComputer.kt:12)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer.computer(DefaultRuleComputer.kt:8)
	at com.itangcent.idea.plugin.api.export.spring.SpringRequestClassExporter.hasApi(SpringRequestClassExporter.kt:55)
	at com.itangcent.idea.plugin.api.export.core.RequestClassExporter.doExport(RequestClassExporter.kt:123)
	at com.itangcent.idea.plugin.api.export.core.RequestClassExporter.export(RequestClassExporter.kt:113)
	at com.itangcent.idea.plugin.api.export.core.CompositeClassExporter.export(CompositeClassExporter.kt:25)
	at com.itangcent.idea.plugin.api.cache.CachedRequestClassExporter.export(CachedRequestClassExporter.kt:56)
	at com.itangcent.idea.plugin.dialog.AbstractApiDashboardDialog$loadApiInClass$1$1.invoke(AbstractApiDashboardDialog.kt:314)
	at com.itangcent.idea.plugin.dialog.AbstractApiDashboardDialog$loadApiInClass$1$1.invoke(AbstractApiDashboardDialog.kt:313)
	at com.itangcent.intellij.extend.ActionContextKitKt.withBoundary(ActionContextKit.kt:61)
	at com.itangcent.idea.plugin.dialog.AbstractApiDashboardDialog$loadApiInClass$1.invoke(AbstractApiDashboardDialog.kt:313)
	at com.itangcent.idea.plugin.dialog.AbstractApiDashboardDialog$loadApiInClass$1.invoke(AbstractApiDashboardDialog.kt:311)
	at com.itangcent.intellij.context.ActionContext.runAsync$lambda$9(ActionContext.kt:215)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

[ERROR]	failed to load config: 
[ERROR]	failed to load config: 
[ERROR]	error in Async
[TRACE]	java.lang.NullPointerException: null cannot be cast to non-null type kotlin.collections.List<kotlin.Function1<com.itangcent.intellij.config.rule.RuleContext, T of com.itangcent.intellij.config.rule.DefaultRuleLookUp.lookUp?>{ com.itangcent.intellij.config.rule.RuleKt.Rule<T of com.itangcent.intellij.config.rule.DefaultRuleLookUp.lookUp> }>
	at com.itangcent.intellij.config.rule.DefaultRuleLookUp.lookUp(DefaultRuleLookUp.kt:41)
	at com.itangcent.intellij.config.rule.RuleLookUpKt.lookUp(RuleLookUp.kt:12)
	at com.itangcent.intellij.config.rule.DefaultRuleComputerKt.lookUp(DefaultRuleComputer.kt:59)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer.doComputer(DefaultRuleComputer.kt:43)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer$computer$1.invoke(DefaultRuleComputer.kt:30)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer$computer$1.invoke(DefaultRuleComputer.kt:28)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry.computerListener(RuleComputeListenerRegistry.kt:34)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry.access$computerListener(RuleComputeListenerRegistry.kt:10)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry$computerListener$1.invoke(RuleComputeListenerRegistry.kt:31)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry$computerListener$1.invoke(RuleComputeListenerRegistry.kt:30)
	at com.itangcent.idea.utils.ContextualPsiClassHelper$InnerComputeListener.computer(ContextualPsiClassHelper.kt:284)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry.computerListener(RuleComputeListenerRegistry.kt:30)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry.computer(RuleComputeListenerRegistry.kt:24)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer.computer(DefaultRuleComputer.kt:28)
	at com.itangcent.intellij.config.rule.RuleComputer$DefaultImpls.computer(RuleComputer.kt:12)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer.computer(DefaultRuleComputer.kt:8)
	at com.itangcent.idea.plugin.api.export.spring.SpringRequestClassExporter.hasApi(SpringRequestClassExporter.kt:55)
	at com.itangcent.idea.plugin.api.export.core.RequestClassExporter.doExport(RequestClassExporter.kt:123)
	at com.itangcent.idea.plugin.api.export.core.RequestClassExporter.export(RequestClassExporter.kt:113)
	at com.itangcent.idea.plugin.api.export.core.CompositeClassExporter.export(CompositeClassExporter.kt:25)
	at com.itangcent.idea.plugin.api.cache.CachedRequestClassExporter.export(CachedRequestClassExporter.kt:56)
	at com.itangcent.idea.plugin.dialog.AbstractApiDashboardDialog$loadApiInClass$1$1.invoke(AbstractApiDashboardDialog.kt:314)
	at com.itangcent.idea.plugin.dialog.AbstractApiDashboardDialog$loadApiInClass$1$1.invoke(AbstractApiDashboardDialog.kt:313)
	at com.itangcent.intellij.extend.ActionContextKitKt.withBoundary(ActionContextKit.kt:61)
	at com.itangcent.idea.plugin.dialog.AbstractApiDashboardDialog$loadApiInClass$1.invoke(AbstractApiDashboardDialog.kt:313)
	at com.itangcent.idea.plugin.dialog.AbstractApiDashboardDialog$loadApiInClass$1.invoke(AbstractApiDashboardDialog.kt:311)
	at com.itangcent.intellij.context.ActionContext.runAsync$lambda$9(ActionContext.kt:215)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

[ERROR]	failed to load config: 
[ERROR]	failed to load config: 

```

**Comment by immadolf** [comment]
这个报错有时候影响接口识别，有时候又不影响，但即使是所有接口都识别成功了，依然会有这些报错
