### ISSUE TITLE
Use JsonReader.setLenient(true) to accept malformed JSON at line 4 column 12 path

### ISSUE THREAD

**Issue by simonpdh** [tangcent/easy-yapi#134]
`	com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 4 column 12 path $
	at com.google.gson.JsonParser.parse(JsonParser.java:65)
	at com.google.gson.JsonParser.parse(JsonParser.java:45)
	at com.itangcent.common.utils.GsonUtils.parseToJsonTree(GsonUtils.kt:51)
	at com.itangcent.idea.plugin.api.export.yapi.AbstractYapiApiHelper.getProjectInfo(AbstractYapiApiHelper.kt:119)
	at com.itangcent.idea.plugin.api.export.yapi.AbstractYapiApiHelper.getProjectIdByToken(AbstractYapiApiHelper.kt:91)
	at com.itangcent.idea.plugin.api.export.yapi.YapiCachedApiHelper.getProjectIdByToken(YapiCachedApiHelper.kt:34)
	at com.itangcent.idea.plugin.api.export.yapi.YapiApiHelper.findCat(YapiApiHelper.kt:40)
	at com.itangcent.idea.plugin.api.export.yapi.AbstractYapiApiExporter.getCartForCls(AbstractYapiApiExporter.kt:95)
	at com.itangcent.idea.plugin.api.export.yapi.AbstractYapiApiExporter.getCartForCls(AbstractYapiApiExporter.kt:63)
	at com.itangcent.idea.plugin.api.export.suv.SuvApiExporter$YapiApiExporterAdapter$SuvYapiApiExporter.getCartForCls(SuvApiExporter.kt:535)
	at com.itangcent.idea.plugin.api.export.yapi.AbstractYapiApiExporter.exportDoc(AbstractYapiApiExporter.kt:120)
	at com.itangcent.idea.plugin.api.export.suv.SuvApiExporter$YapiApiExporterAdapter.doExportDocs(SuvApiExporter.kt:514)
	at com.itangcent.idea.plugin.api.export.suv.SuvApiExporter$ApiExporterAdapter$doExportApisFromMethod$2.invoke(SuvApiExporter.kt:335)
	at com.itangcent.idea.plugin.api.export.suv.SuvApiExporter$ApiExporterAdapter$doExportApisFromMethod$2.invoke(SuvApiExporter.kt:166)
	at com.itangcent.intellij.context.ActionContext$runAsync$2.run(ActionContext.kt:173)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 4 column 12 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1409)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
	at com.google.gson.JsonParser.parse(JsonParser.java:60)
	... 19 more

上传api时候报错` @tangcent

**Comment by tangcent** [comment]
hi~
这里需要更多信息才能确认问题所在.
https://github.com/tangcent/easy-yapi/commit/dc4b176d7712e6029567aef06756ef932720beed

---

我网络有点问题,github上传不了
你可以自行打包插件或者到这里下:
链接: https://pan.baidu.com/s/1qJ56oCcKWb_lqtbltni18A 提取码: frh4

**Comment by simonpdh** [comment]
我用的是easy-yapi.1.6.0.0.183.0.jar，idea是2019.2.4，jdk是1.8，年前都可以，年后就不行 了

**Comment by tangcent** [comment]
理解，不过这里需要一点信息才能确认问题所在
https://github.com/tangcent/easy-yapi/compare/fix/%23134#diff-d09bf86211dc1988f1ec2f37cd712ed4

```kotlin
logger!!.error("error to parse project [$projectId] info:$ret")
```
需要确认一下这里发生错误的project信息是什么样的
下面的链接是包含这个commit的打包.
链接: https://pan.baidu.com/s/1qJ56oCcKWb_lqtbltni18A 提取码: frh4

---

另外，是否所有的接口上传时都会有这个情况?

**Comment by simonpdh** [comment]
是的，所有能检测到的接口上传都是，只有@GetMapping这种情况检测不到接口，@GetMapping("/aaaa")这样可以检测到，还有你所说的项目信息是是指什么信息？

**Comment by tangcent** [comment]
> 还有你所说的项目信息是是指什么信息？

这里的`项目信息`是指`yapi`中当前项目的信息.也是这里报错的原因.
针对这个报错，我昨天加了段日志代码:
https://github.com/tangcent/easy-yapi/compare/fix/%23134#diff-d09bf86211dc1988f1ec2f37cd712ed4
```
logger!!.error("error to parse project [$projectId] info:$ret")
```
上面这一段代码不在release里，也就是你从中央仓库下载的插件中不含有这个`commit`.
所以需要你下载上面我提供的插件(包含这个`commit`),再尝试解析上传接口一次.
应该会在控制台打印出`("error to parse project [$projectId] info:$ret")`这段信息
需要依据这段信息来判断出错的具体原因以及如何修复此问题.

---

从报错情况来看，是获取项目信息后无法解析导致的.
除了依靠上述手段以外，你还可以尝试在`yapi`中重新新建一个新的空项目,在`IDEA`中更换当前模块的`token`，将接口导入新的空项目试试.

**Comment by simonpdh** [comment]
error to parse project [null] info:这个是你那个jar打出的日志信息

**Comment by tangcent** [comment]
`projectId`为`null`一般是调用通过`token`取`project`基本信息的接口:
https://hellosean1025.github.io/yapi/openapi.html

是否可以本地尝试访问`{yapi_host} /api/project/get?token={your_token}`?
(ps:你可以隐去所有的业务信息)

**Comment by tangcent** [comment]
在设置中可以清楚本地缓存:
http://easyyapi.com/setting/ide-setting.html
为了减少不必要的网络请求，插件会将token与projectId的对应关系缓存在本地.
这部分代码在:
https://github.com/tangcent/easy-yapi/blob/master/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiCachedApiHelper.kt

**Comment by simonpdh** [comment]
我觉得有可能是我电脑的代理问题

**Comment by tangcent** [comment]
是否已解决?

**Comment by simonpdh** [comment]
未解决，该插件是否支持设置header，再请求对应的服务器的时候？

**Comment by tangcent** [comment]
> 未解决，该插件是否支持设置header，再请求对应的服务器的时候？@tangcent
---

> 未解决

还是无法上传到yapi吗?

> 该插件是否支持设置header，再请求对应的服务器的时候？

是指插件请求yapi服务还是为yapi中的api设置header?

也许是指这个? http://easyyapi.com/setting/rules/method_additional_header.html

**Comment by simonpdh** [comment]
是请求yapi服务器的时候要先设置header鉴权后才能访问yapi服务器，也就是中间还有一层权限限制，如果可以设置header应该是可以访问yapi服务器的

**Comment by tangcent** [comment]
- 目前没有相关配置可用.

- 如果访问yapi服务器需要额外的header鉴权，那yapi的web页面是如何做到鉴权的呢?

---

- 也许可以通过本地nginx代理来加上需要的header?

**Comment by simonpdh** [comment]
其实只要提供一个header配置项即可，我测试过，在idea的httpclient工具带上cookie是剋访问的，我只要把浏览器的cookie复制进去即可用，但我看插件还不支持这个

**Comment by tangcent** [comment]
目前来说插件依赖的是yapi的openapi: https://hellosean1025.github.io/yapi/openapi.html
所有的鉴权都是通过`项目token`来完成的.
插件也只拥有开发者填入的`token`能访问的对用的项目信息.不会尝试也不能够获取到开发者账号其他相关信息.最大程度的保证信息安全.

---

- 你这里的授权是指`yapi`的授权还是运维附加的(比如nginx)?
- 目前使用的`yapi`版本号是多少?yapi对token进行过一次大的更新，更新前token位数较短,更新后token位数加长, openapi也新增了很多.所以对于很久之前的版本，有可能是无法支持的.
可以尝试访问`{yapi_host} /api/project/get?token={your_token}`,如果本地请求这个链接不通而且`token`是对的话，那应该就是`yapi`版本过低.
- 填入cookie有点麻烦且授权范围过大.倒是考虑过填用户名密码.但目前来说提供`token`是个更好的方案.

**Comment by simonpdh** [comment]
你理解错我的意思了，是访问yapi服务器之前公司层面有一层鉴权，外网访问内网，需要鉴权，跟yapi本身没关系

**Comment by tangcent** [comment]
> 你理解错我的意思了，是访问yapi服务器之前公司层面有一层鉴权，外网访问内网，需要鉴权，跟yapi本身没关系

理解了. 如[comment-587345951](https://github.com/tangcent/easy-yapi/issues/134#issuecomment-587345951) 所述,目前来说是否可以通过本地nginx代理来加上所需要的header?

---

- 要从插件层面来配置的话，需要考虑到这个功能大部分开发者可能是不需要的。
- 如果改造一下`YapiApiHelper`，给出一个请求前回调方法`preCall`.
然后允许开发者通过[groovy本地扩展](http://easyyapi.com/setting/groovy-ext-config.html)来重载`preCall`以达到任意篡改http请求是否可行?

**Comment by simonpdh** [comment]
recommend可否拓展一个这样的配置让大家自主选择

**Comment by tangcent** [comment]
see https://github.com/tangcent/easy-yapi/compare/fix/%23134

[easy-yapi.1.6.0.0.183.0.jar.zip](https://github.com/tangcent/easy-yapi/files/4219339/easy-yapi.1.6.0.0.183.0.jar.zip)

---

[groovy本地扩展](http://easyyapi.com/setting/groovy-ext-config.html)

- 在项目目录下创建 /.easyapi/ext

- 创建扩展文件 `YapiExportActionExt.groovy`

```groovy
import com.intellij.psi.*
import com.itangcent.idea.plugin.api.export.yapi.YapiApiHelper
import com.itangcent.idea.plugin.api.export.yapi.YapiCachedApiHelper
import com.itangcent.idea.plugin.script.ActionExt
import com.itangcent.idea.plugin.utils.KtHelper
import com.itangcent.intellij.context.ActionContext
import org.apache.http.client.methods.HttpRequestBase

class YapiExportActionExt implements ActionExt {

    void init(ActionContext.ActionContextBuilder builder) {

        builder.bind(YapiApiHelper.class, KtHelper.INSTANCE.ktFunction({
            it.to(CustomYapiApiHelper.class).in(com.google.inject.Singleton.class)
            return null
        }))

    }

    static class CustomYapiApiHelper extends YapiCachedApiHelper {

        protected void beforeCall(HttpRequestBase httpRequest) {
            logger.info("beforeCall")
            //这里写自定义代码
//            httpRequest.setHeader("cookie", "test")

        }
    }
}
```

**Comment by simonpdh** [comment]
恩，谢谢，我暂时先用着这个，希望后续这个能抽成界面化，这个配置有点重

**Comment by duanpeizhou** [comment]
我也遇到了这个问题  什么时候发版呢？

**Comment by tangcent** [comment]
> 我也遇到了这个问题 什么时候发版呢？

hi~,你是碰到这个错误:` com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException`
还是也有`访问yapi服务器的额外鉴权需求`?

**Comment by duanpeizhou** [comment]
我是碰到了错误
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $

导入到postman  是可以的    导入到Yapi  就报这个错

EasyYapi版本：
1.6.0.0.183.0

Idea版本：
IntelliJ IDEA 2019.2.4 (Ultimate Edition)
Build #IU-192.7142.36, built on October 29, 2019

**Comment by tangcent** [comment]
- 如果不是和`simonpdh`一样需要额外授权的话，可能是`yapi`的`server`配置有误.
- 一般来说`token`如果配置有误应该是可以提醒到`token`失效的

---

检查一下配置的[server](http://easyyapi.com/setting/ide-setting.html),这个地址应该是可访问的.
可以尝试清除本地缓存
可以尝试清空设置的`token`

[新的版本](https://github.com/tangcent/easy-yapi/releases/tag/v1.7.0.0)

**Comment by duanpeizhou** [comment]
问题解决了，公司内网有SSO，也是要加cookie的。
谢谢

**Comment by tangcent** [comment]
有使用[yapi-plugin-qsso](https://github.com/YMFE/yapi-plugin-qsso)吗?

**Comment by tangcent** [comment]
hi~,支持了http相关的两个配置

pr:https://github.com/tangcent/easy-api/pull/257

---

可以尝试这样配置:利用`request.header(name,value)`&`httpClient.cookieStore()`应该可以满足你们的需求.

http.call.before=groovy:```
logger.info("call:"+request.url())
```

[easy-yapi.1.8.0.0.183.0.jar.zip](https://github.com/tangcent/easy-yapi/files/4351861/easy-yapi.1.8.0.0.183.0.jar.zip)

**Comment by simonpdh** [comment]
好的，谢谢，辛苦了
