### ISSUE TITLE
Idea插件easyYapi生成文档报Gson错误

### ISSUE THREAD

**Issue by jerryi1** [tangcent/easy-yapi#256]
**之前用的没有报错，就是这次创建一个新的项目。配置新的token就出错了。能帮忙看看什么原因？**

```
[ERROR]	Post failed:com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $
	at com.google.gson.JsonParser.parse(JsonParser.java:65)
	at com.google.gson.JsonParser.parse(JsonParser.java:45)
	at com.itangcent.common.utils.GsonUtils.parseToJsonTree(GsonUtils.kt:51)
	at com.itangcent.intellij.extend.GsonKitKt.asJsonElement(GsonKit.kt:58)
	at com.itangcent.idea.plugin.api.export.yapi.DefaultYapiApiHelper.addCart(DefaultYapiApiHelper.kt:119)
	at com.itangcent.idea.plugin.api.export.yapi.DefaultYapiApiHelper.addCart(DefaultYapiApiHelper.kt:98)
	at com.itangcent.idea.plugin.api.export.yapi.AbstractYapiApiExporter.getCartForDoc(AbstractYapiApiExporter.kt:86)
	at com.itangcent.idea.plugin.api.export.suv.SuvApiExporter$YapiApiExporterAdapter$SuvYapiApiExporter.getCartForDoc(SuvApiExporter.kt:528)
	at com.itangcent.idea.plugin.api.export.yapi.AbstractYapiApiExporter.getCartForDoc(AbstractYapiApiExporter.kt:67)
	at com.itangcent.idea.plugin.api.export.yapi.AbstractYapiApiExporter.exportDoc(AbstractYapiApiExporter.kt:104)
	at com.itangcent.idea.plugin.api.export.suv.SuvApiExporter$YapiApiExporterAdapter.doExportDocs(SuvApiExporter.kt:511)
	at com.itangcent.idea.plugin.api.export.suv.SuvApiExporter$ApiExporterAdapter$doExportApisFromMethod$2.invoke(SuvApiExporter.kt:333)
	at com.itangcent.idea.plugin.api.export.suv.SuvApiExporter$ApiExporterAdapter$doExportApisFromMethod$2.invoke(SuvApiExporter.kt:164)
	at com.itangcent.intellij.context.ActionContext$runAsync$2.run(ActionContext.kt:173)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1409)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
	at com.google.gson.JsonParser.parse(JsonParser.java:60)
	... 18 more
```

**Comment by tangcent** [comment]
这个可能是http请求错误, 先排查一下:

- 检查一下网络, 是否有设置代理之类的
- 用浏览器打开yapi地址看看是不是通的
- 尝试移除最近添加的token
- 尝试升级插件到最新版本

**Comment by jerryi1** [comment]
> 这个可能是http请求错误, 先排查一下:
> 
> * 检查一下网络, 是否有设置代理之类的
> * 用浏览器打开yapi地址看看是不是通的
> * 尝试移除最近添加的token
> * 尝试升级插件到最新版本

1 easyYapi插件刚才升级过了。
2 网络从有线换成wifi了
3 网址是能正常打开的。
好像还是不行

**Comment by jerryi1** [comment]
> **之前用的没有报错，就是这次创建一个新的项目。配置新的token就出错了。能帮忙看看什么原因？**
> 
> ```
> [ERROR]	Post failed:com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $
> 	at com.google.gson.JsonParser.parse(JsonParser.java:65)
> 	at com.google.gson.JsonParser.parse(JsonParser.java:45)
> 	at com.itangcent.common.utils.GsonUtils.parseToJsonTree(GsonUtils.kt:51)
> 	at com.itangcent.intellij.extend.GsonKitKt.asJsonElement(GsonKit.kt:58)
> 	at com.itangcent.idea.plugin.api.export.yapi.DefaultYapiApiHelper.addCart(DefaultYapiApiHelper.kt:119)
> 	at com.itangcent.idea.plugin.api.export.yapi.DefaultYapiApiHelper.addCart(DefaultYapiApiHelper.kt:98)
> 	at com.itangcent.idea.plugin.api.export.yapi.AbstractYapiApiExporter.getCartForDoc(AbstractYapiApiExporter.kt:86)
> 	at com.itangcent.idea.plugin.api.export.suv.SuvApiExporter$YapiApiExporterAdapter$SuvYapiApiExporter.getCartForDoc(SuvApiExporter.kt:528)
> 	at com.itangcent.idea.plugin.api.export.yapi.AbstractYapiApiExporter.getCartForDoc(AbstractYapiApiExporter.kt:67)
> 	at com.itangcent.idea.plugin.api.export.yapi.AbstractYapiApiExporter.exportDoc(AbstractYapiApiExporter.kt:104)
> 	at com.itangcent.idea.plugin.api.export.suv.SuvApiExporter$YapiApiExporterAdapter.doExportDocs(SuvApiExporter.kt:511)
> 	at com.itangcent.idea.plugin.api.export.suv.SuvApiExporter$ApiExporterAdapter$doExportApisFromMethod$2.invoke(SuvApiExporter.kt:333)
> 	at com.itangcent.idea.plugin.api.export.suv.SuvApiExporter$ApiExporterAdapter$doExportApisFromMethod$2.invoke(SuvApiExporter.kt:164)
> 	at com.itangcent.intellij.context.ActionContext$runAsync$2.run(ActionContext.kt:173)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $
> 	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
> 	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1409)
> 	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542)
> 	at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
> 	at com.google.gson.JsonParser.parse(JsonParser.java:60)
> 	... 18 more
> ```

**Comment by jerryi1** [comment]
> 这个可能是http请求错误, 先排查一下:
> 
> * 检查一下网络, 是否有设置代理之类的
> * 用浏览器打开yapi地址看看是不是通的
> * 尝试移除最近添加的token
> * 尝试升级插件到最新版本

测试了一下，导入到postman是可以的

**Comment by tangcent** [comment]
可以尝试临时加以下配置,来看插件发出的http请求以定位问题:
``````
http.call.before=groovy:```
    logger.info("[start]url:"+ request.url());
```
http.call.after=groovy:```
    logger.info("[end]url:"+ request.url() +"\nresponse:"+response.string());
```
``````

**Comment by jerryi1** [comment]
> 可以尝试临时加以下配置,来看插件发出的http请求以定位问题:
> 
> ```
> http.call.before=groovy:```
>     logger.info("[start]url:"+ request.url());
> ```
> http.call.after=groovy:```
>     logger.info("[end]url:"+ request.url() +"\nresponse:"+response.string());
> ```
> ```
找到原因了，原本请求是http的，现在网站换成https了。http请求返回的301.
**解决了，谢谢**
