### ISSUE TITLE
期望多环境下的maven项目导出文档不提示警告

### ISSUE THREAD

**Issue by Semoz** [tangcent/easy-yapi#331]
EasyYapi:`2.1.2.183.0` , IDEA 2019.2

`application.yml`配置文件中存在多环境的写法
```
spring:
  application:
    name: project
  profiles:
    active: @profile.active@
```

CTRL + E导出文档出现警告提示，不影响导出功能
```
run easy-yapi
[INFO]	Start find apis...
[TRACE]	find config file:.easy.api.config
[WARN]	load yaml failed
[TRACE]	while scanning for the next token
found character '@' that cannot start any token. (Do not use @ for indentation)
 in 'reader', line 9, column 13:
        active: @profile.active@
                ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:418)
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:227)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValue.produce(ParserImpl.java:586)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:124)
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:236)
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:227)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:215)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144)
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:236)
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:227)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:215)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144)
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:236)
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:227)
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:215)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144)
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:85)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getData(BaseConstructor.java:125)
	at org.yaml.snakeyaml.Yaml$1.next(Yaml.java:548)
	at com.itangcent.intellij.config.AbstractConfigReader.loadYamlConfig(AbstractConfigReader.kt:116)
	at com.itangcent.intellij.config.AbstractConfigReader.loadConfigInfoContent(AbstractConfigReader.kt:48)
	at com.itangcent.intellij.config.AbstractConfigReader.loadConfigFile(AbstractConfigReader.kt:144)
	at com.itangcent.intellij.config.AbstractConfigReader.parseEqualLine(AbstractConfigReader.kt:92)
	at com.itangcent.intellij.config.AbstractConfigReader.access$parseEqualLine(AbstractConfigReader.kt:13)
	at com.itangcent.intellij.config.AbstractConfigReader$loadPropertiesConfig$1.invoke(AbstractConfigReader.kt:82)
	at com.itangcent.intellij.config.AbstractConfigReader$loadPropertiesConfig$1.invoke(AbstractConfigReader.kt:13)
	at com.itangcent.intellij.config.LineReader.lines(LineReader.kt:26)
	at com.itangcent.intellij.config.AbstractConfigReader.loadPropertiesConfig(AbstractConfigReader.kt:83)
	at com.itangcent.intellij.config.AbstractConfigReader.loadConfigInfoContent(AbstractConfigReader.kt:54)
	at com.itangcent.intellij.config.MutableConfigReader$DefaultImpls.loadConfigInfoContent(MutableConfigReader.kt:13)
	at com.itangcent.intellij.config.AbstractConfigReader.loadConfigInfoContent(AbstractConfigReader.kt:13)
	at com.itangcent.idea.plugin.config.RecommendConfigReader.initDelegateAndRecommend(RecommendConfigReader.kt:126)
	at com.itangcent.idea.plugin.config.RecommendConfigReader.access$initDelegateAndRecommend(RecommendConfigReader.kt:20)
	at com.itangcent.idea.plugin.config.RecommendConfigReader$init$1.invoke(RecommendConfigReader.kt:89)
	at com.itangcent.idea.plugin.config.RecommendConfigReader$init$1.invoke(RecommendConfigReader.kt:20)
	at com.itangcent.intellij.psi.DefaultContextSwitchListener$onModuleChange$1.invoke(DefaultContextSwitchListener.kt:60)
	at com.itangcent.intellij.psi.DefaultContextSwitchListener$onModuleChange$1.invoke(DefaultContextSwitchListener.kt:11)
	at com.itangcent.intellij.psi.DefaultContextSwitchListener.switchTo(DefaultContextSwitchListener.kt:40)
	at com.itangcent.intellij.psi.SelectedHelper$Builder.onFile(SelectedHelper.kt:153)
	at com.itangcent.intellij.psi.SelectedHelper$Builder.access$onFile(SelectedHelper.kt:23)
	at com.itangcent.intellij.psi.SelectedHelper$Builder$traversal$2.invoke(SelectedHelper.kt:87)
	at com.itangcent.intellij.psi.SelectedHelper$Builder$traversal$2.invoke(SelectedHelper.kt:23)
	at com.itangcent.intellij.context.ActionContext$runInReadUI$1.run(ActionContext.kt:373)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:53)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:936)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:53)
	at com.itangcent.intellij.context.ActionContext.runInReadUI(ActionContext.kt:367)
	at com.itangcent.intellij.psi.SelectedHelper$Builder.traversal(SelectedHelper.kt:78)
	at com.itangcent.idea.plugin.api.export.suv.SuvApiExporter.showExportWindow(SuvApiExporter.kt:130)
	at com.itangcent.idea.plugin.actions.SuvExportAction.actionPerformed(SuvExportAction.kt:69)
	at com.itangcent.intellij.actions.KotlinAnAction$actionPerformed$2.invoke(KotlinAnAction.kt:48)
	at com.itangcent.intellij.actions.KotlinAnAction$actionPerformed$2.invoke(KotlinAnAction.kt:17)
	at com.itangcent.intellij.context.ActionContext$runAsync$2.run(ActionContext.kt:190)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

[INFO]	use recommend config
[INFO]	search api from:com.company.project.controller.account.AccountController

Process finished with exit code 0

```
希望能支持这种写法，不提示警告
（ps.已知去掉设置中的`EasyApi -> General -> use recommend config` 的勾选就只会显示INFO和TRACE）

**Comment by tangcent** [comment]
- 目前还没有跳过`yaml`无法解析token的解决方案
- 这里你可以尝试:
  - 在[setting](http://easyyapi.com/setting/ide-setting.html)里将日志级别调整到`MEDIUM`
  - 或者在`recommend config`中移除勾选`import_spring_properties`

**Comment by Semoz** [comment]
了解
