### ISSUE TITLE
反馈一个BUG:当 REST-API 为 GET 请求、且方法中存在 模型对象参数时，ALT+SHIFT+E 生成API文档时插件会抛出异常

### ISSUE THREAD

**Issue by cjw0511** [tangcent/easy-yapi#380]
反馈一个BUG，当 REST-API 为 GET 请求、且方法中存在 模型对象参数时，ALT+SHIFT+E 生成API文档时插件会抛出异常

run easy-yapi
[INFO]	Start find apis...
[TRACE]	find config file:E:\Workspaces\git\gitlab\hose\hmall\taxi\mall-hcar\mall-hcar-taxi\mall-hcar-taxi-webserver\.easy.api.config
[INFO]	use recommend config
[INFO]	search api from:com.hose.mall.hcar.taxi.webserver.controllers.common.token.TaxiCommonTokenController
[TRACE]	find config file:E:\Workspaces\git\gitlab\hose\hmall\taxi\mall-hcar\mall-hcar-taxi\mall-hcar-taxi-webserver\.easy.api.config
[INFO]	use recommend config
[INFO]	search api from:com.hose.mall.hcar.taxi.webserver.controllers.common.token.TaxiCommonTokenController
[ERROR]	error to parse[com.hose.mall.hcar.taxi.model.basics.UserInclusion] as Querys
[TRACE]	java.lang.ClassCastException: class java.util.HashMap cannot be cast to class com.itangcent.common.utils.KV (java.util.HashMap is in module java.base of loader 'bootstrap'; com.itangcent.common.utils.KV is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @17a45728)
	at com.itangcent.idea.plugin.api.export.yapi.YapiSpringRequestClassExporter.addParamAsQuery(YapiSpringRequestClassExporter.kt:277)
	at com.itangcent.idea.plugin.api.export.yapi.YapiSpringRequestClassExporter.processMethodParameter(YapiSpringRequestClassExporter.kt:181)
	at com.itangcent.idea.plugin.api.export.AbstractRequestClassExporter.processMethodParameters(AbstractRequestClassExporter.kt:450)
	at com.itangcent.idea.plugin.api.export.AbstractRequestClassExporter.exportMethodApi(AbstractRequestClassExporter.kt:182)
	at com.itangcent.idea.plugin.api.export.AbstractRequestClassExporter.access$exportMethodApi(AbstractRequestClassExporter.kt:38)
	at com.itangcent.idea.plugin.api.export.AbstractRequestClassExporter$export$1.invoke(AbstractRequestClassExporter.kt:142)
	at com.itangcent.idea.plugin.api.export.AbstractRequestClassExporter$export$1.invoke(AbstractRequestClassExporter.kt:38)
	at com.itangcent.idea.plugin.api.ClassApiExporterHelper$sam$java_util_function_Consumer$0.accept(ClassApiExporterHelper.kt)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at com.itangcent.idea.plugin.api.ClassApiExporterHelper.foreachMethod(ClassApiExporterHelper.kt:103)
	at com.itangcent.idea.plugin.api.export.AbstractRequestClassExporter.export(AbstractRequestClassExporter.kt:138)
	at com.itangcent.idea.plugin.api.export.ClassExporter$DefaultImpls.export(ClassExporter.kt:14)
	at com.itangcent.idea.plugin.api.export.AbstractRequestClassExporter.export(AbstractRequestClassExporter.kt:38)
	at com.itangcent.idea.plugin.api.export.ComboClassExporter$export$ret$1.apply(ComboClassExporter.kt:42)
	at com.itangcent.idea.plugin.api.export.ComboClassExporter$export$ret$1.apply(ComboClassExporter.kt:15)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:528)
	at com.itangcent.idea.plugin.api.export.ComboClassExporter.export(ComboClassExporter.kt:43)
	at com.itangcent.idea.plugin.api.export.ClassExporter$DefaultImpls.export(ClassExporter.kt:14)
	at com.itangcent.idea.plugin.api.export.ComboClassExporter.export(ComboClassExporter.kt:15)
	at com.itangcent.idea.plugin.api.export.suv.SuvApiExporter$ApiExporterAdapter.doExportApisFromMethod(SuvApiExporter.kt:322)
	at com.itangcent.idea.plugin.api.export.suv.SuvApiExporter$ApiExporterAdapter.access$doExportApisFromMethod(SuvApiExporter.kt:167)
	at com.itangcent.idea.plugin.api.export.suv.SuvApiExporter$ApiExporterAdapter$exportApisFromMethod$1$1$1$1.invoke(SuvApiExporter.kt:225)
	at com.itangcent.idea.plugin.api.export.suv.SuvApiExporter$ApiExporterAdapter$exportApisFromMethod$1$1$1$1.invoke(SuvApiExporter.kt:167)
	at com.itangcent.intellij.context.ActionContext$runInReadUI$1.run(ActionContext.kt:346)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:52)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:889)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:51)
	at com.itangcent.intellij.context.ActionContext.runInReadUI(ActionContext.kt:340)
	at com.itangcent.idea.plugin.api.export.suv.SuvApiExporter$ApiExporterAdapter$exportApisFromMethod$1$1$1.invoke(SuvApiExporter.kt:223)
	at com.itangcent.idea.plugin.api.export.suv.SuvApiExporter$ApiExporterAdapter$exportApisFromMethod$1$1$1.invoke(SuvApiExporter.kt:167)
	at com.itangcent.idea.plugin.api.export.suv.SuvApiExporter$YapiApiExporterAdapter.beforeExport(SuvApiExporter.kt:495)
	at com.itangcent.idea.plugin.api.export.suv.SuvApiExporter$ApiExporterAdapter$exportApisFromMethod$1$1.invoke(SuvApiExporter.kt:222)
	at com.itangcent.idea.plugin.api.export.suv.SuvApiExporter$ApiExporterAdapter$exportApisFromMethod$1$1.invoke(SuvApiExporter.kt:167)
	at com.itangcent.intellij.context.ActionContext$runAsync$2.run(ActionContext.kt:183)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

[INFO]	Add new cart: https://xxxxxxxxxxxxxxxx
[INFO]	Export to https: //xxxxxxxxxxxxxxxxxxx

Process finished with exit code 0

**Comment by cjw0511** [comment]
重新提交
