### ISSUE TITLE
导出到markdown 报StackOverflowError

### ISSUE THREAD

**Issue by HaiziGe** [tangcent/easy-yapi#392]
**Describe the bug**
导出到markdown 报StackOverflowError

**To Reproduce**
最新版本 2.8.1
点击导出到markdown 报StackOverflowError

错误日志
run easy-yapi
[INFO]	Start find apis...
[TRACE]	No config be found
[INFO]	use recommend config
[INFO]	search api from:com.xxxxx.FinanceDataController
[INFO]	try infer return type of method[com.xxxxx.controller.FinanceDataController#getPage(com.baomidou.mybatisplus.extension.plugins.pagination.Page,com.xxxxx.FinanceData,java.lang.String)]
[ERROR]	error to parse body
[TRACE]	java.lang.StackOverflowError
	at com.itangcent.idea.plugin.api.DefaultMethodInferHelper$MappedVariable.getComputedValue(DefaultMethodInferHelper.kt:846)
	at com.itangcent.idea.plugin.api.DefaultMethodInferHelper$AbstractVariable.getValue(DefaultMethodInferHelper.kt:817)
	at com.itangcent.idea.plugin.api.DefaultMethodInferHelper$Companion.valueOf(DefaultMethodInferHelper.kt:567)
	at com.itangcent.idea.plugin.api.DefaultMethodInferHelper$Companion.valueOf(DefaultMethodInferHelper.kt:567)
	at com.itangcent.idea.plugin.api.DefaultMethodInferHelper$Companion.valueOf(DefaultMethodInferHelper.kt:567)
	at com.itangcent.idea.plugin.api.DefaultMethodInferHelper$Companion.valueOf(DefaultMethodInferHelper.kt:567)
	at com.itangcent.idea.plugin.api.DefaultMethodInferHelper$Companion.valueOf(DefaultMethodInferHelper.kt:567)
	at com.itangcent.idea.plugin.api.DefaultMethodInferHelper$Companion.valueOf(DefaultMethodInferHelper.kt:567)
	at com.itangcent.idea.plugin.api.DefaultMethodInferHelper$Companion.valueOf(DefaultMethodInferHelper.kt:567)
	at com.itangcent.idea.plugin.api.DefaultMethodInferHelper$Companion.valueOf(DefaultMethodInferHelper.kt:567)
	at com.itangcent.idea.plugin.api.DefaultMethodInferHelper$Companion.valueOf(DefaultMethodInferHelper.kt:567)
	。。。。。。。。。。。。。。。。
	at com.itangcent.idea.plugin.api.DefaultMethodInferHelper$Companion.valueOf(DefaultMethodInferHelper.kt:567)
	at com.itangcent.idea.plugin.api.DefaultMethodInferHelper$Companion.valueOf(DefaultMethodInferHelper.kt:567)

[INFO]	Start parse apis
[INFO]	Apis save success: D:/project\easy-api.md

这是业务代码
    @GetMapping("/page")
    public R getPage(Page page, FinanceData financeData, String updateTimeStr) {
                  /*  -------------*/
}

**Comment by tangcent** [comment]
我会在稍晚些时候review.

请先关闭智能推断: http://easyyapi.com/setting/ide-setting.html

![image](https://user-images.githubusercontent.com/17569144/86461766-0fa06700-bd5d-11ea-8f4d-691cc55afa0d.png)
