### ISSUE TITLE
IDEA 2020.3.3 版本有报错

### ISSUE THREAD

**Issue by superleeyom** [tangcent/easy-yapi#417]
插件版本：2.1.9.183.0
idea 版本：2020.3.3
上传接口会报：
```
[ERROR]	Apis export failed
[TRACE]	java.lang.ClassNotFoundException: {"c":"java.lang.String" PluginClassLoader[PluginDescriptor(name=EasyYapi, id=com.itangcent.idea.plugin.easy-yapi, path=/Users/leeyom/Library/Application Support/JetBrains/IntelliJIdea2020.3/plugins/EasyYapi, version=2.1.9.183.0)] com.intellij.ide.plugins.cl.PluginClassLoader@1566b63f
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:129)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at com.itangcent.idea.utils.JacksonUtils.fromJson(JacksonUtils.kt:33)
	at com.itangcent.idea.binder.DbBeanBinderFactory$DbBeanBinder.read(DbBeanBinder.kt:60)
	at com.itangcent.idea.plugin.api.export.yapi.YapiCachedApiHelper.getProjectIdByToken(YapiCachedApiHelper.kt:31)
	at com.itangcent.idea.plugin.api.export.yapi.AbstractYapiApiHelper.getProjectInfo(AbstractYapiApiHelper.kt:161)
	at com.itangcent.idea.plugin.api.export.yapi.AbstractYapiApiHelper.getPrivateToken(AbstractYapiApiHelper.kt:244)
	at com.itangcent.idea.plugin.api.export.yapi.AbstractYapiApiExporter.getTokenOfModule(AbstractYapiApiExporter.kt:55)
	at com.itangcent.idea.plugin.api.export.yapi.AbstractYapiApiExporter.getCartForResource(AbstractYapiApiExporter.kt:66)
	at com.itangcent.idea.plugin.api.export.yapi.AbstractYapiApiExporter.exportDoc(AbstractYapiApiExporter.kt:115)
	at com.itangcent.idea.plugin.api.export.suv.SuvApiExporter$YapiApiExporterAdapter.doExportDocs(SuvApiExporter.kt:509)
	at com.itangcent.idea.plugin.api.export.suv.SuvApiExporter$ApiExporterAdapter$doExportApisFromMethod$2.invoke(SuvApiExporter.kt:338)
	at com.itangcent.idea.plugin.api.export.suv.SuvApiExporter$ApiExporterAdapter$doExportApisFromMethod$2.invoke(SuvApiExporter.kt:167)
	at com.itangcent.intellij.context.ActionContext$runAsync$2.run(ActionContext.kt:183)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
麻烦有空帮忙看看呗？辛苦了

**Comment by superleeyom** [comment]
插件版本降级到2.1.8就正常了，可能是IDEA版本过高导致

**Comment by tangcent** [comment]
应该是插件类加载器的隔离导致的

**Comment by tangcent** [comment]
抱歉~想错了。
是对旧版本插件缓存的兼容问题.
see https://github.com/tangcent/easy-yapi/issues/418

**Comment by superleeyom** [comment]
> 抱歉~想错了。
> 是对旧版本插件缓存的兼容问题.
> see #418

已解决，感谢
