### ISSUE TITLE
Export Yapi不支持mac m1芯片版本

### ISSUE THREAD

**Issue by lkqm** [tangcent/easy-yapi#424]
[ERROR]	error to export api from method:upload
[TRACE]	java.sql.SQLException: Error opening connection
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:215)
	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:25)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:24)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
	at org.sqlite.JDBC.createConnection(JDBC.java:114)
	at org.sqlite.SQLiteDataSource.getConnection(SQLiteDataSource.java:410)
	at org.sqlite.SQLiteDataSource.getConnection(SQLiteDataSource.java:398)
	at com.itangcent.idea.sqlite.SqliteDataResourceHelperKt.execute(SqliteDataResourceHelper.kt:281)
	at com.itangcent.idea.sqlite.SqliteDataResourceHelper$SimpleBeanDAOImpl$1.invoke(SqliteDataResourceHelper.kt:85)
	at com.itangcent.idea.sqlite.SqliteDataResourceHelper$SimpleBeanDAOImpl$1.invoke(SqliteDataResourceHelper.kt:72)
	at com.itangcent.idea.sqlite.SQLiteDataSourceHandle.write(SqliteDataResourceHelper.kt:259)
	at com.itangcent.idea.sqlite.SqliteDataResourceHelper$SimpleBeanDAOImpl.<init>(SqliteDataResourceHelper.kt:85)
	at com.itangcent.idea.sqlite.SqliteDataResourceHelper.getSimpleBeanDAO(SqliteDataResourceHelper.kt:56)
	at com.itangcent.idea.binder.DbBeanBinderFactory.getDAO(DbBeanBinder.kt:31)
	at com.itangcent.idea.binder.DbBeanBinderFactory.access$getDAO(DbBeanBinder.kt:10)
	at com.itangcent.idea.binder.DbBeanBinderFactory$DbBeanBinder.read(DbBeanBinder.kt:58)
	at com.itangcent.idea.plugin.api.export.yapi.YapiCachedApiHelper.getProjectIdByToken(YapiCachedApiHelper.kt:31)
	at com.itangcent.idea.plugin.api.export.yapi.AbstractYapiApiHelper.getProjectInfo(AbstractYapiApiHelper.kt:161)
	at com.itangcent.idea.plugin.api.export.yapi.AbstractYapiApiHelper.getPrivateToken(AbstractYapiApiHelper.kt:244)
	at com.itangcent.idea.plugin.api.export.yapi.AbstractYapiApiExporter.getTokenOfModule(AbstractYapiApiExporter.kt:55)
	at com.itangcent.idea.plugin.api.export.yapi.AbstractYapiApiExporter.getCartForResource(AbstractYapiApiExporter.kt:66)
	at com.itangcent.idea.plugin.api.export.yapi.AbstractYapiApiExporter.exportDoc(AbstractYapiApiExporter.kt:115)
	at com.itangcent.idea.plugin.api.export.yapi.YapiApiExporter$doExport$3$1.invoke(YapiApiExporter.kt:58)
	at com.itangcent.idea.plugin.api.export.yapi.YapiApiExporter$doExport$3$1.invoke(YapiApiExporter.kt:17)
	at com.itangcent.idea.plugin.api.export.AbstractRequestClassExporter.exportMethodApi(AbstractRequestClassExporter.kt:188)
	at com.itangcent.idea.plugin.api.export.AbstractRequestClassExporter.access$exportMethodApi(AbstractRequestClassExporter.kt:38)
	at com.itangcent.idea.plugin.api.export.AbstractRequestClassExporter$export$1.invoke(AbstractRequestClassExporter.kt:142)
	at com.itangcent.idea.plugin.api.export.AbstractRequestClassExporter$export$1.invoke(AbstractRequestClassExporter.kt:38)
	at com.itangcent.idea.plugin.api.ClassApiExporterHelper$sam$java_util_function_Consumer$0.accept(ClassApiExporterHelper.kt)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at com.itangcent.idea.plugin.api.ClassApiExporterHelper.foreachMethod(ClassApiExporterHelper.kt:103)
	at com.itangcent.idea.plugin.api.export.AbstractRequestClassExporter.export(AbstractRequestClassExporter.kt:138)
	at com.itangcent.idea.plugin.api.export.ClassExporter$DefaultImpls.export(ClassExporter.kt:14)
	at com.itangcent.idea.plugin.api.export.AbstractRequestClassExporter.export(AbstractRequestClassExporter.kt:38)
	at com.itangcent.idea.plugin.api.export.ComboClassExporter$export$ret$1.apply(ComboClassExporter.kt:42)
	at com.itangcent.idea.plugin.api.export.ComboClassExporter$export$ret$1.apply(ComboClassExporter.kt:15)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:528)
	at com.itangcent.idea.plugin.api.export.ComboClassExporter.export(ComboClassExporter.kt:43)
	at com.itangcent.idea.plugin.api.export.ClassExporter$DefaultImpls.export(ClassExporter.kt:14)
	at com.itangcent.idea.plugin.api.export.ComboClassExporter.export(ComboClassExporter.kt:15)
	at com.itangcent.idea.plugin.api.export.yapi.YapiApiExporter$doExport$3.invoke(YapiApiExporter.kt:58)
	at com.itangcent.idea.plugin.api.export.yapi.YapiApiExporter$doExport$3.invoke(YapiApiExporter.kt:17)
	at com.itangcent.intellij.psi.SelectedHelper$Builder$onFile$1.invoke(SelectedHelper.kt:158)
	at com.itangcent.intellij.psi.SelectedHelper$Builder$onFile$1.invoke(SelectedHelper.kt:23)
	at com.itangcent.intellij.context.ActionContext$runInReadUI$1.run(ActionContext.kt:346)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:52)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:885)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:51)
	at com.itangcent.intellij.context.ActionContext.runInReadUI(ActionContext.kt:340)
	at com.itangcent.intellij.psi.SelectedHelper$Builder.onFile(SelectedHelper.kt:156)
	at com.itangcent.intellij.psi.SelectedHelper$Builder.access$onFile(SelectedHelper.kt:23)
	at com.itangcent.intellij.psi.SelectedHelper$Builder$traversal$2.invoke(SelectedHelper.kt:87)
	at com.itangcent.intellij.psi.SelectedHelper$Builder$traversal$2.invoke(SelectedHelper.kt:23)
	at com.itangcent.intellij.context.ActionContext$runInReadUI$1.run(ActionContext.kt:346)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:52)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:889)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:51)
	at com.itangcent.intellij.context.ActionContext.runInReadUI(ActionContext.kt:340)
	at com.itangcent.intellij.psi.SelectedHelper$Builder.traversal(SelectedHelper.kt:78)
	at com.itangcent.idea.plugin.api.export.yapi.YapiApiExporter.doExport(YapiApiExporter.kt:66)
	at com.itangcent.idea.plugin.api.export.yapi.YapiApiExporter.export(YapiApiExporter.kt:22)
	at com.itangcent.idea.plugin.actions.YapiExportAction.actionPerformed(YapiExportAction.kt:45)
	at com.itangcent.intellij.actions.KotlinAnAction$actionPerformed$2.invoke(KotlinAnAction.kt:48)
	at com.itangcent.intellij.actions.KotlinAnAction$actionPerformed$2.invoke(KotlinAnAction.kt:17)
	at com.itangcent.intellij.context.ActionContext$runAsync$2.run(ActionContext.kt:183)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.Exception: No native library is found for os.name=Mac and os.arch=aarch64. path=/org/sqlite/native/Mac/aarch64
	at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:333)
	at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:64)
	at org.sqlite.core.NativeDB.load(NativeDB.java:56)
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:211)
	... 92 more

**Comment by tangcent** [comment]
ref: https://youtrack.jetbrains.com/issue/DBE-12342

---

你在使用的idea版本号是多少?
从现在的情况来看，指定3.34.0+的`sqlite`依赖即可解决。
但是`idea`本身自带了`sqlite`依赖，所以一般插件都不需要额外打包`sqlite`依赖。
`easy-yapi`对sqlite的使用并非为必须的，是可以使用`localfile`来实现替代。
所以现在的疑问是如果最新版的`idea`是否已经升级了`sqlite`依赖，以此来决定采取哪种方案。

**Comment by lkqm** [comment]
IntelliJ IDEA 2020.3.3 (Ultimate Edition)
Build #IU-203.7717.56, built on March 15, 2021
Licensed to IntelliJ IDEA Evaluator
Expiration date: May 5, 2021
Runtime version: 11.0.10+8-b1145.96 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.2
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8

**Comment by tangcent** [comment]
New branch: https://github.com/tangcent/easy-yapi/tree/compatibale/apple-m1
Plug-in package with latest `sqlite`:[easy-yapi-2.1.9.183.0.zip](https://github.com/tangcent/easy-yapi/files/6258743/easy-yapi-2.1.9.183.0.zip)

---

Note:  Plug-in package with the latest `sqlite` is too large，So this commit will be reverted when the new update of `IntelliJ IDEA` for Apple Silicon fixed the problem.
