### ISSUE TITLE
接口使用 Enum 类型 export to yapi 僵死

### ISSUE THREAD

**Issue by clarkhan** [tangcent/easy-yapi#56]
## 环境：
> 插件使用目前最新版（Version 1.0.0.183.0.0）
> IntelliJ IDEA 2019.2 (Ultimate Edition)
> Build #IU-192.5728.98, built on July 23, 2019
> Runtime version: 1.8.0_201-b09 amd64

## 现象：
执行 export 后，日志输出如下：
![](https://cdn.nlark.com/yuque/0/2019/png/328984/1569486222460-da48da5e-21e5-4729-b512-55beffb6de6f.png)

同时，占用资源迅速飙升到配置上限：
![1569486125383-4a0ee9b1-93f8-486b-8990-3f7c8e74013e.png](https://cdn.nlark.com/yuque/0/2019/png/328984/1569486125383-4a0ee9b1-93f8-486b-8990-3f7c8e74013e.png)

Intellij 基本僵死，无后续反应。

在执行操作时进行 CPU 抽样，可以见到如下信息：
![](https://cdn.nlark.com/yuque/0/2019/png/328984/1569486280767-f8866648-b668-4c15-8cbe-25e8e7235aa9.png)

相关 thread dump 如下：
```
"ActionContext-1" #226 daemon prio=5 os_prio=0 tid=0x000000006fc92000 nid=0x4144 runnable [0x000000005644b000]
   java.lang.Thread.State: RUNNABLE
        at java.util.HashSet.<init>(HashSet.java:106)
        at kotlin.reflect.jvm.internal.impl.utils.DFS$VisitedWithSet.<init>(DFS.java:136)
        at kotlin.reflect.jvm.internal.impl.utils.DFS.dfs(DFS.java:37)
        at kotlin.reflect.jvm.internal.impl.utils.DFS.ifAny(DFS.java:47)
        at kotlin.reflect.jvm.internal.impl.resolve.descriptorUtil.DescriptorUtilsKt.declaresOrInheritsDefaultValue(DescriptorUtils.kt:188)
        at kotlin.reflect.jvm.internal.KParameterImpl.isOptional(KParameterImpl.kt:61)
        at kotlin.reflect.full.KClasses.createInstance(KClasses.kt:280)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper.copy(AbstractPsiClassHelper.kt:73)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper$copy$2.accept(AbstractPsiClassHelper.kt:82)
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper.copy(AbstractPsiClassHelper.kt:81)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper.copy(AbstractPsiClassHelper.kt:74)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper$copy$2.accept(AbstractPsiClassHelper.kt:82)
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper.copy(AbstractPsiClassHelper.kt:81)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper.copy(AbstractPsiClassHelper.kt:74)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper$copy$2.accept(AbstractPsiClassHelper.kt:82)
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper.copy(AbstractPsiClassHelper.kt:81)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper$copy$2.accept(AbstractPsiClassHelper.kt:82)
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper.copy(AbstractPsiClassHelper.kt:81)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper.copy(AbstractPsiClassHelper.kt:74)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper$copy$2.accept(AbstractPsiClassHelper.kt:82)
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper.copy(AbstractPsiClassHelper.kt:81)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper$copy$2.accept(AbstractPsiClassHelper.kt:82)
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper.copy(AbstractPsiClassHelper.kt:81)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper$copy$2.accept(AbstractPsiClassHelper.kt:82)
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper.copy(AbstractPsiClassHelper.kt:81)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper$copy$2.accept(AbstractPsiClassHelper.kt:82)
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper.copy(AbstractPsiClassHelper.kt:81)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper$copy$2.accept(AbstractPsiClassHelper.kt:82)
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper.copy(AbstractPsiClassHelper.kt:81)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper$copy$2.accept(AbstractPsiClassHelper.kt:82)
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper.copy(AbstractPsiClassHelper.kt:81)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper$copy$2.accept(AbstractPsiClassHelper.kt:82)
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper.copy(AbstractPsiClassHelper.kt:81)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper$copy$2.accept(AbstractPsiClassHelper.kt:82)
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper.copy(AbstractPsiClassHelper.kt:81)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper$copy$2.accept(AbstractPsiClassHelper.kt:82)
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper.copy(AbstractPsiClassHelper.kt:81)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper$copy$2.accept(AbstractPsiClassHelper.kt:82)
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper.copy(AbstractPsiClassHelper.kt:81)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper$copy$2.accept(AbstractPsiClassHelper.kt:82)
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper.copy(AbstractPsiClassHelper.kt:81)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper.copy(AbstractPsiClassHelper.kt:74)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper$copy$2.accept(AbstractPsiClassHelper.kt:82)
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper.copy(AbstractPsiClassHelper.kt:81)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper$copy$2.accept(AbstractPsiClassHelper.kt:82)
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper.copy(AbstractPsiClassHelper.kt:81)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper.getFields(AbstractPsiClassHelper.kt:253)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper.parseFieldOrMethod(AbstractPsiClassHelper.kt:1052)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper$getFields$2.invoke(AbstractPsiClassHelper.kt:462)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper$getFields$2.invoke(AbstractPsiClassHelper.kt:25)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper.foreachField(AbstractPsiClassHelper.kt:496)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper.getFields(AbstractPsiClassHelper.kt:445)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper.getTypeObject(AbstractPsiClassHelper.kt:421)
        at com.itangcent.idea.utils.CustomizedPsiClassHelper.getTypeObject(CustomizedPsiClassHelper.kt:39)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper.getTypeObject(AbstractPsiClassHelper.kt:274)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper.getTypeObject(AbstractPsiClassHelper.kt:332)
        at com.itangcent.idea.utils.CustomizedPsiClassHelper.getTypeObject(CustomizedPsiClassHelper.kt:39)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper.getTypeObject(AbstractPsiClassHelper.kt:274)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper.parseFieldOrMethod(AbstractPsiClassHelper.kt:971)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper$getFields$2.invoke(AbstractPsiClassHelper.kt:462)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper$getFields$2.invoke(AbstractPsiClassHelper.kt:25)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper.foreachField(AbstractPsiClassHelper.kt:496)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper.getFields(AbstractPsiClassHelper.kt:445)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper.getTypeObject(AbstractPsiClassHelper.kt:421)
        at com.itangcent.idea.utils.CustomizedPsiClassHelper.getTypeObject(CustomizedPsiClassHelper.kt:39)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper.getTypeObject(AbstractPsiClassHelper.kt:274)
        at com.itangcent.intellij.psi.AbstractPsiClassHelper.getTypeObject(AbstractPsiClassHelper.kt:182)
        at com.itangcent.idea.plugin.api.export.AbstractRequestClassExporter.parseResponseBody(AbstractRequestClassExporter.kt:407)
        at com.itangcent.idea.plugin.api.export.AbstractRequestClassExporter.processResponse(AbstractRequestClassExporter.kt:200)
        at com.itangcent.idea.plugin.api.export.AbstractRequestClassExporter.exportMethodApi(AbstractRequestClassExporter.kt:150)
        at com.itangcent.idea.plugin.api.export.AbstractRequestClassExporter.access$exportMethodApi(AbstractRequestClassExporter.kt:32)
        at com.itangcent.idea.plugin.api.export.AbstractRequestClassExporter$export$1.invoke(AbstractRequestClassExporter.kt:114)
        at com.itangcent.idea.plugin.api.export.AbstractRequestClassExporter$export$1.invoke(AbstractRequestClassExporter.kt:32)
        at com.itangcent.idea.plugin.api.export.AbstractRequestClassExporter.foreachMethod(AbstractRequestClassExporter.kt:455)
        at com.itangcent.idea.plugin.api.export.AbstractRequestClassExporter.export(AbstractRequestClassExporter.kt:112)
        at com.itangcent.idea.plugin.api.export.ComboClassExporter$export$1.apply(ComboClassExporter.kt:38)
        at com.itangcent.idea.plugin.api.export.ComboClassExporter$export$1.apply(ComboClassExporter.kt:13)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)
        at com.itangcent.idea.plugin.api.export.ComboClassExporter.export(ComboClassExporter.kt:38)
        at com.itangcent.idea.plugin.api.export.yapi.YapiApiExporter$doExport$3.invoke(YapiApiExporter.kt:65)
        at com.itangcent.idea.plugin.api.export.yapi.YapiApiExporter$doExport$3.invoke(YapiApiExporter.kt:13)
        at com.itangcent.intellij.psi.SelectedHelper$Builder$onFile$1.invoke(SelectedHelper.kt:144)
        at com.itangcent.intellij.psi.SelectedHelper$Builder$onFile$1.invoke(SelectedHelper.kt:22)
        at com.itangcent.intellij.context.ActionContext$runInReadUI$1.run(ActionContext.kt:314)
        at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:53)
        at com.intellij.openapi.application.ReadAction$$Lambda$960/699603244.compute(Unknown Source)
        at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:932)
        at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
        at com.intellij.openapi.application.ReadAction.run(ReadAction.java:53)
        at com.itangcent.intellij.context.ActionContext.runInReadUI(ActionContext.kt:308)
        at com.itangcent.intellij.psi.SelectedHelper$Builder.onFile(SelectedHelper.kt:142)
        at com.itangcent.intellij.psi.SelectedHelper$Builder.access$onFile(SelectedHelper.kt:22)
        at com.itangcent.intellij.psi.SelectedHelper$Builder$traversal$2.invoke(SelectedHelper.kt:78)
        at com.itangcent.intellij.psi.SelectedHelper$Builder$traversal$2.invoke(SelectedHelper.kt:22)
        at com.itangcent.intellij.context.ActionContext$runInReadUI$1.run(ActionContext.kt:314)
        at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:53)
        at com.intellij.openapi.application.ReadAction$$Lambda$960/699603244.compute(Unknown Source)
        at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:936)
        at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
        at com.intellij.openapi.application.ReadAction.run(ReadAction.java:53)
        at com.itangcent.intellij.context.ActionContext.runInReadUI(ActionContext.kt:308)
        at com.itangcent.intellij.psi.SelectedHelper$Builder.traversal(SelectedHelper.kt:72)
        at com.itangcent.idea.plugin.api.export.yapi.YapiApiExporter.doExport(YapiApiExporter.kt:73)
        at com.itangcent.idea.plugin.api.export.yapi.YapiApiExporter.export(YapiApiExporter.kt:18)
        at com.itangcent.idea.plugin.actions.YapiExportAction.actionPerformed(YapiExportAction.kt:40)
        at com.itangcent.intellij.actions.KotlinAnAction$actionPerformed$2.invoke(KotlinAnAction.kt:49)
        at com.itangcent.intellij.actions.KotlinAnAction$actionPerformed$2.invoke(KotlinAnAction.kt:17)
        at com.itangcent.intellij.context.ActionContext$runAsync$2.run(ActionContext.kt:169)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

对比验证，该情况和返回类型相关。export 正常的代码：
```java
@RestController
@RequestMapping("/testJava")
public class TestJavaController {

    @GetMapping("/suc")
    public SucDTO suc() {
        return null;
    }

}

class SucDTO {
    private String field;

    public String getField() {
        return field;
    }

    public void setField(String field) {
        this.field = field;
    }
}

```

异常的代码：
```java
@RestController
@RequestMapping("/test")
public class TestJavaController {

    @GetMapping("/failed")
    public FailedDTO failed() {
        return null;
    }

}

class FailedDTO {
    private SomeEnum field;

    public SomeEnum getField() {
        return field;
    }

    public void setField(SomeEnum field) {
        this.field = field;
    }
}

enum SomeEnum {
    ONE, TWO
}
```

初步判断是对 Enum 解析的问题。
自己搭建插件 debug 环境总是抛`com.itangcent.intellij.extend.guice.InjectorsKt.withUnsafe`相关异常，暂未进一步分析。

**Comment by tangcent** [comment]
- 确实没考虑到这种需求.抱歉~
- 目前来说可以增加配置来暂时规避解析enum导致的异常
```
json.rule.convert[your enum class]=java.lang.String
```

---

- see https://www.zhihu.com/question/52760637
- 根据spring的基础规则`枚举默认使用字面量`,我将增加enum默认转换为string,并自动mock可用枚举值
- 但是很多在spring中使用enum时貌似会加入`Converter/ConverterFactory`,
自动解析`Converter/ConverterFactory`有点困难，可能还是需要提供配置规则来配置可行度高一点
- 我考虑增加如下配置规则
```
#json.rule.enum.convert[your enum class]=your enum class#value field
json.rule.enum.convert[com.itangcent.common.constant.UserType]=com.itangcent.common.constant.UserType#type
#可简写为
json.rule.enum.convert[com.itangcent.common.constant.UserType]=#type
```
将DTO/VO中的`UserType`类型的字段如
`private UserType type;//用户类型`
解析效果与如下定义类似
```
    /**
     * @see com.itangcent.common.constant.UserType
     */
    private int type;//用户类型
```
- 如果希望使用ordina，可以如下配置:
```
json.rule.enum.convert[com.itangcent.common.constant.UserType]=#ordinal()
```
- 意下如何?

**Comment by clarkhan** [comment]
```
#json.rule.enum.convert[your enum class]=your enum class#value field
json.rule.enum.convert[com.itangcent.common.constant.UserType]=com.itangcent.common.constant.UserType#type
#可简写为
json.rule.enum.convert[com.itangcent.common.constant.UserType]=#type
```
这种方式很棒。
如果此处的配置可以支持接口配置适应于所有实现就更好了。比如系统中一批 Enum 都实现了某个接口 `WithCodeEnumInterface`，都有 `getCode` 方法：
```java
public interface WithCodeEnumInterface {
    int getCode();
}

enum SomeEnum implements WithCodeEnumInterface {
    A(1),
    B(2);

    private int code;
    SomeEnum(int code) {
        this.code = code;
    }
    @Override
    public int getCode() {
        return this.code;
    }
}
```

这样就可以统一处理了。
当然，可能现在更多推荐的方式是不在接口中使用 Enum，而非在序列化反序列化中处理。所以对于 Enum  的处理可能是个小众需求吧

**Comment by tangcent** [comment]
这种需求是不是可以这样表达:
```
json.rule.enum.convert[groovy:it.extend("WithCodeEnumInterface")]=#getCode()
```

**Comment by tangcent** [comment]
- 基础的解析功能将在easy-api中完成 https://github.com/tangcent/easy-api/issues/134
- easy-yapi将针对yapi做额外处理，如mock

**Comment by clarkhan** [comment]
> 这种需求是不是可以这样表达:
> 
> ```
> json.rule.enum.convert[groovy:it.extend("WithCodeEnumInterface")]=#getCode()
> ```

可以~

**Comment by qinkangdeid** [comment]
> ```
> #json.rule.enum.convert[your enum class]=your enum class#value field
> json.rule.enum.convert[com.itangcent.common.constant.UserType]=com.itangcent.common.constant.UserType#type
> #可简写为
> json.rule.enum.convert[com.itangcent.common.constant.UserType]=#type
> ```
> 
> 这种方式很棒。
> 如果此处的配置可以支持接口配置适应于所有实现就更好了。比如系统中一批 Enum 都实现了某个接口 `WithCodeEnumInterface`，都有 `getCode` 方法：
> 
> ```java
> public interface WithCodeEnumInterface {
>     int getCode();
> }
> 
> enum SomeEnum implements WithCodeEnumInterface {
>     A(1),
>     B(2);
> 
>     private int code;
>     SomeEnum(int code) {
>         this.code = code;
>     }
>     @Override
>     public int getCode() {
>         return this.code;
>     }
> }
> ```
> 
> 这样就可以统一处理了。
> 当然，可能现在更多推荐的方式是不在接口中使用 Enum，而非在序列化反序列化中处理。所以对于 Enum 的处理可能是个小众需求吧

大佬 我也遇到了你的这个问题  我感觉枚举作为入参 应该是可行的  枚举做入参天生将具备参数合法性校验的能力 枚举参数给什么 对接方将传什么 可以很好的避免乱传 瞎传  阿里巴巴手册也提到了这一点 枚举做入参没问题 出参的话这个倒是有些博弈

**Comment by tangcent** [comment]
最近有点忙~断断续续的只写了一点点，这个周日希望能抽出时间把这个支持写完.

**Comment by qinkangdeid** [comment]
> 最近有点忙~断断续续的只写了一点点，这个周日希望能抽出时间把这个支持写完.

好的 感谢🙏

**Comment by qinkangdeid** [comment]
感谢大佬  更新用了新版本  对于 @RequestBody 注解的参数对象含有枚举可以解析了  把枚举属性的注释都列出来了 非常喜欢这样 很棒
![image](https://user-images.githubusercontent.com/17582522/67256224-81c76900-f4b8-11e9-856c-3840c93f25de.png)


 但 `@RequestParam `和 `@PathVariable `(这种情况很少) 注解的枚举参数 没能把 枚举 枚举备注 解释在其他信息里面 
我的项目大量使用了枚举做参数 类似下面：
```java
  /**
     * 测试枚举作为表单参数RequestParam
     *
     * @param enumVal 枚举值：ONE：一 TWO：二  {@link TestEnum}
     * @return com.baibu.framework2.net.DataResponse<com.baibu.order.web.controller.order.baibu.TestBean>
     */
    @PostMapping("getByEnum")
    public DataResponse<TestBean> getByEnumRequestParam(@RequestParam TestEnum enumVal) {
        return DataResponse.ok(new TestBean());
    }


    /**
     * 测试枚举作为路径参数
     *
     * @param enumVal 枚举值：ONE：一 TWO：二   {@link TestEnum}
     * @return com.baibu.framework2.net.DataResponse<com.baibu.order.web.controller.order.baibu.TestBean>
     */
    @PostMapping("{enumVal}}")
    public DataResponse<TestBean> getByEnumPathVariable(@PathVariable TestEnum enumVal) {
        return DataResponse.ok(new TestBean());
    }
```
如果和body对象里的枚举解析格式一样的话 枚举参数值就不用在@param 把枚举值罗列在那里了  
再次感谢大佬提供这么棒的插件   🙏

**Comment by tangcent** [comment]
- 嗯，这一波改动蛮多的，我把rule的解析模式做了重构
- 使得支持`name[filter]=value`这样的语法
- 相对的，因为底层规则变动而受到影响的地方也蛮多的，所以接下来会收集此版本的bug(哈哈哈，主要都是我自己用的过程中发现的~)，迭代几个小版本
- 你可以新开一个issue:  对于`@RequestParam` 和 `@PathVariable `使用到枚举的支持
- 你还可以把你的实例代码提交到[spring-demo](https://github.com/Earth-1610/spring-demo)
- 另外，关于枚举的规则配置文档我还没写..基本上和当前issue中设定的差不多:
```
json.rule.enum.convert[com.itangcent.common.constant.UserType]=~#type
```
