### ISSUE TITLE
[Bug] export to yapi,get an error,java.lang.StackOverflowError

### ISSUE THREAD

**Issue by wowo404** [tangcent/easy-yapi#679]
**Describe the bug**

export to yapi, StackOverflowError occurred.

**Logs**

1. Add config:
the config is original,i just config the yapi server and tokens   

2. Console output `easy_api`
   the log level is low
   
3. stacktrace

**run easy-yapi
[INFO]	Start find apis...
[INFO]	search api from:com.joolun.cloud.mall.admin.controller.MallGoodsSpuController
[TRACE]	No config be found
[INFO]	use recommend config
[INFO]	search api from:com.joolun.cloud.mall.admin.controller.MallGoodsSpuController
[ERROR]	error to export apis:null
[TRACE]	java.lang.StackOverflowError
	at java.base/java.lang.AbstractStringBuilder.putStringAt(AbstractStringBuilder.java:1665)
	at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:539)
	at java.base/java.lang.StringBuffer.append(StringBuffer.java:312)
	at java.base/java.io.StringWriter.write(StringWriter.java:106)
	at com.google.gson.stream.JsonWriter.string(JsonWriter.java:566)
	at com.google.gson.stream.JsonWriter.writeDeferredName(JsonWriter.java:402)
	at com.google.gson.stream.JsonWriter.beginObject(JsonWriter.java:307)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:205)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:145)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:208)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:145)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:245)
	at com.google.gson.internal.bind.ObjectTypeAdapter.write(ObjectTypeAdapter.java:107)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97)**

i didn't copy the duplicate stacktrace.

**Environment:**
 - OS: [Windows]
 - IDEA version [2019.3.1]
 - Plugin version [2.3.1.183.0]
 - Yapi version [1.9.2]

**Demo Code**
`/**
 * 商城商品
 * @Author lzs
 * @Date 2021/12/18 15:38
 * @module mall-admin
 **/
@RequiredArgsConstructor
@Slf4j
@RestController
@RequestMapping("mallGoodsSpu")
public class MallGoodsSpuController {

	private final GoodsSpuService goodsSpuService;

	/**
	 * 列表--给新增订单使用
	 * @param page
	 * @param req
	 * @return
	 */
	@GetMapping("pageListForOrder")
	public R<Page<GoodsSpuListForOrderResp>> pageListForOrder(Page<GoodsSpuListForOrderResp> page, GoodsSpuListForOrderReq req){
		return R.ok(goodsSpuService.pageListForOrder(page, req));
	}

}`

`@Data
public class GoodsSpuListForOrderResp {
	/**
	 * 商品信息
	 */
	private SpuInfo spuInfo;
	/**
	 * 套系信息
	 */
	private MallPackage packageInfo;

	@Data
	public static class SpuInfo {
		/**
		 * spuId
		 */
		private String id;
		/**
		 * 商品图片
		 */
		private String[] picUrls;
		/**
		 * spu名字
		 */
		private String name;
		/**
		 * sku列表
		 */
		private List<SkuInfo> skuList;
	}

	@Data
	public static class SkuInfo {
		/**
		 * skuId
		 */
		private String id;
		/**
		 * 销售价格
		 */
		private BigDecimal salesPrice;
		/**
		 * 规格信息
		 */
		private String specInfo;
		/**
		 * sku图片
		 */
		private String picUrl;
	}
}`
the class of reqeust args is normal,i didn't copy

**Comment by tangcent** [comment]
It seems difficult to reproduce the bug based on your provide demo code.
![image](https://user-images.githubusercontent.com/17569144/147672583-4ad49a67-6215-4b77-b6db-053985b598e2.png)

Please consider providing a spring project to reproduce this bug.
You can fork the demo project: https://github.com/Earth-1610/spring-demo
Any more info which can help to reproduce the bug is welcome.
