### ISSUE TITLE
无参枚举解析异常

### ISSUE THREAD

**Issue by just-a-stone** [tangcent/easy-yapi#741]
**Describe the question**

每次解析无参枚举时报错，请问怎么处理
操作：
`to Json5`
配置：默认推荐配置

枚举示例：
```java
// BaseEnum是一个空接口。  用作标记
public enum CalculationBaseEnum implements BaseEnum {
    A,
    B,
    C,
    D,
}
```

报错如下
CalculationBaseEnum 是FinCostDetails的一个属性

```java
run easy-yapi
[ERROR]	error to getTypeObject:PsiType:FinCostDetails
[TRACE]	java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy222.resolveEnumFields(Unknown Source)
	at com.itangcent.intellij.psi.AbstractPsiClassHelper.parseEnumConstant(AbstractPsiClassHelper.kt:825)
	at com.itangcent.intellij.psi.AbstractPsiClassHelper.resolveEnumOrStatic(AbstractPsiClassHelper.kt:675)
	at com.itangcent.intellij.psi.DefaultPsiClassHelper.getTypeObject(DefaultPsiClassHelper.kt:206)
	at com.itangcent.intellij.psi.AbstractPsiClassHelper.doGetTypeObject(AbstractPsiClassHelper.kt:242)
	at com.itangcent.intellij.psi.AbstractPsiClassHelper.parseFieldOrMethod(AbstractPsiClassHelper.kt:948)
	at com.itangcent.intellij.psi.DefaultPsiClassHelper.parseFieldOrMethod(DefaultPsiClassHelper.kt:318)
	at com.itangcent.intellij.psi.AbstractPsiClassHelper$doGetFields$1.invoke(AbstractPsiClassHelper.kt:316)
	at com.itangcent.intellij.psi.AbstractPsiClassHelper$doGetFields$1.invoke(AbstractPsiClassHelper.kt:28)
	at com.itangcent.intellij.psi.AbstractPsiClassHelper.foreachField(AbstractPsiClassHelper.kt:531)
	at com.itangcent.intellij.psi.AbstractPsiClassHelper.doGetFields(AbstractPsiClassHelper.kt:307)
	at com.itangcent.intellij.psi.AbstractPsiClassHelper.doGetFields(AbstractPsiClassHelper.kt:273)
	at com.itangcent.intellij.psi.AbstractPsiClassHelper.doGetTypeObject(AbstractPsiClassHelper.kt:203)
	at com.itangcent.intellij.psi.AbstractPsiClassHelper.getTypeObject(AbstractPsiClassHelper.kt:92)
	at com.itangcent.idea.plugin.actions.FieldsToJson5Action.formatMessage(FieldsToJson5Action.kt:24)
	at com.itangcent.idea.plugin.actions.FieldsToMessageAction$actionPerformed$1.invoke(FieldsToMessageAction.kt:80)
	at com.itangcent.idea.plugin.actions.FieldsToMessageAction$actionPerformed$1.invoke(FieldsToMessageAction.kt:35)
	at com.itangcent.intellij.context.ActionContext$runInWriteUI$1.run(ActionContext.kt:293)
	at com.intellij.openapi.command.WriteCommandAction.lambda$runWriteCommandAction$4(WriteCommandAction.java:361)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.lambda$doRunWriteCommandAction$1(WriteCommandAction.java:150)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:947)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.lambda$doRunWriteCommandAction$2(WriteCommandAction.java:148)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:219)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:184)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.doRunWriteCommandAction(WriteCommandAction.java:157)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.lambda$run$0(WriteCommandAction.java:128)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeAndWait$7(ApplicationImpl.java:450)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:131)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:187)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.itangcent.common.spi.ProxyBean$invoke$ret$1.invoke(ProxyBean.kt:21)
	at com.itangcent.common.spi.ProxyBean$invoke$ret$1.invoke(ProxyBean.kt:9)
	at com.itangcent.common.utils.ReflectKitKt.privileged(ReflectKit.kt:349)
	at com.itangcent.common.spi.ProxyBean.invoke(ProxyBean.kt:21)
	at com.itangcent.common.spi.ProxyBean.invoke(ProxyBean.kt:12)
	... 56 more
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated array at line 1 column 7 path $[1]
	at com.google.gson.Gson.fromJson(Gson.java:947)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at com.itangcent.common.utils.GsonUtils.fromJson(GsonUtils.kt:78)
	at com.itangcent.intellij.jvm.standard.StandardEnumFieldResolverImpl.resolveWithoutConstruct(StandardEnumFieldResolver.kt:158)
	at com.itangcent.intellij.jvm.standard.StandardEnumFieldResolverImpl.resolveEnumFields(StandardEnumFieldResolver.kt:27)
	at com.itangcent.intellij.jvm.standard.StandardPsiResolver.resolveEnumFields(StandardPsiResolver.kt:309)
	... 65 more
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated array at line 1 column 7 path $[1]
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:475)
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:413)
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:71)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	... 72 more
```

据我观察
直接对`CalculationBaseEnum`  使用 `to json5`
结果如下：
run easy-yapi

""

猜测：空字符串无法被解析为枚举。 报错

**Comment by tangcent** [comment]
`com.itangcent.intellij.jvm.standard.StandardEnumFieldResolverImpl.resolveWithoutConstruct`这里是解析没有关联源码的枚举类，你可以尝试在idea中打开这个枚举类`CalculationBaseEnum`, 在右上角`Download Source`试试。

`解析没有关联源码的枚举`是这个版本新加的特性，你可以从[Jetbrains](https://plugins.jetbrains.com/plugin/12458-easyyapi/versions)或者[github](https://github.com/tangcent/easy-yapi/releases)下载以前的版本使用。

我很难重现这个问题，你能不能提供这个类的内容(在未点击右上角`Download Source`之前的内容，即`.class`的内容)? 你可以用`Xxx`替换掉敏感信息。

**Comment by just-a-stone** [comment]
1. 疑惑：CalculationBaseEnum 和 FinCostDetails 在不同子模块，但是在同一个父项目中。idea中点击也能直接跳转。`应该能关联到源码`。         实际上，在解决问题前。我通过在`CalculationBaseEnum` 移除`FinCostDetails`的 `import`, 保留字段报红，此时能够生成json
2. 重新安装V2.3.2 `问题解决`

另一个使用问题：
我在idea中，配置如下。但是`to json5`时，`@ApiModelProperty(value = "字段名",example = "1")` 不能被解析
看起来就像，`field.doc=@io.swagger.annotations.ApiModelProperty#value` 不生效
```text
#properties.additional=https://raw.githubusercontent.com/tangcent/easy-yapi/master/third/javax.validation.mock.config
#properties.additional=https://raw.githubusercontent.com/tangcent/easy-yapi/master/third/swagger.config
properties.additional=https://raw.githubusercontent.com/tangcent/easy-yapi/master/third/swagger.advanced.config
```

**Comment by tangcent** [comment]
我没办法重现这个问题:
https://github.com/Earth-1610/web-demo/blob/master/cn/springboot-demo/src/main/java/com/itangcent/springboot/demo/swagger/dto/SwaggerModel.java
<img width="288" alt="image" src="https://user-images.githubusercontent.com/17569144/163198312-fae7d24c-559f-4843-ab16-ccfe0a9e108a.png">

---

1. 你使用的`swagger`版本中,`io.swagger.annotations.ApiModelProperty`包名是否一致?
2. 如果是github连接问题，可以试试替换成`https://gitee.com/tangcent/easy-yapi/raw/master/third/swagger.config`

**Comment by just-a-stone** [comment]
`ApiModelProperty` 是github连接问题。 搞定   

thanks...
