### ISSUE TITLE
[Question] 导出到postman报错，之前可以正常导出，今天突然不行了

### ISSUE THREAD

**Issue by 314537485** [tangcent/easy-yapi#799]
**之前正常导入到postman，今天突然不行了，不知道为何，postman的token正常配着**

之前一直通过idea生成postman接口文档，今天生成的时候报错了
**提前说明：**
1.之前是可以正常导出到postman上的
2.postman的token已经配置
3.trust hosts已经配置了如下内容
```
https://api.getpostman.com
http://localhost
http://127.0.0.1
https://localhost
https://127.0.0.1
```

**错误信息如下：**
[INFO]	PrivateToken of postman be found
[ERROR]	[WLError] 1 attribute is invalid
[ERROR]	Export to postman failed. You could check below:
1.the network 
2.the privateToken

[INFO]	Apis exported completed
[INFO]	Exported data are copied to clipboard, you can paste to postman now
[INFO]	Api data is too lager to show in console

**期望得到解答是什么原因**

期待有人遇到过可以给解答一下，谢谢！

**Comment by tangcent** [comment]
试试导出其他接口。确认一下是所有接口无法导出还是某些接口无法导出?

---

> [ERROR] [WLError] 1 attribute is invalid

这个有可能是导出的APi中包含一些特殊字符没有处理。

> [INFO] Exported data are copied to clipboard, you can paste to postman now

可以提供这里的`Exported data`吗？你可以将其中的敏感信息打码处理。

**Comment by 314537485** [comment]
请问这个 **Exported data** 在哪找到啊？

**Comment by 314537485** [comment]
> 试试导出其他接口。确认一下是所有接口无法导出还是某些接口无法导出?

试了一下 ，有部分接口可以导出，所以应该不是配置的问题

**Comment by tangcent** [comment]
> 请问这个 **Exported data** 在哪找到啊？

直接Ctrl+V就可以

**Comment by 314537485** [comment]
而且我发现了端倪，就是一个controller中有**2个接口**，**我注释掉任何一个都可以导成功**，2个一起导出则提示**那个错误**

这是那个controller中2个接口导出的 **Exported data** 如下：
```
{
  "item": [
    {
      "item": [
        {
          "request": {
            "method": "POST",
            "description": "",
            "header": [
              {
                "key": "Content-Type",
                "value": "application/json",
                "type": "text",
                "description": ""
              }
            ],
            "body": {
              "mode": "raw",
              "options": {
                "raw": {
                  "language": "json"
                }
              },
              "raw": "{}"
            },
            "url": {
              "path": [
                "homepage",
                "overview"
              ],
              "query": [],
              "host": "{{platform-web}}",
              "raw": "{{platform-web}}/homepage/overview"
            }
          },
          "response": [
            {
              "originalRequest": {
                "method": "POST",
                "description": "",
                "header": [
                  {
                    "key": "Content-Type",
                    "value": "application/json",
                    "type": "text",
                    "description": ""
                  }
                ],
                "body": {
                  "mode": "raw",
                  "options": {
                    "raw": {
                      "language": "json"
                    }
                  },
                  "raw": "{}"
                },
                "url": {
                  "query": [],
                  "host": "{{platform-web}}"
                }
              },
              "_postman_previewlanguage": "json",
              "code": 200,
              "_postman_previewtype": "text",
              "responseTime": 24,
              "name": "首页-数据概览-Example",
              "header": [
                {
                  "name": "date",
                  "key": "date",
                  "value": "周五, 22 7月 202211:10:41 GMT",
                  "description": "The date and time that the message was sent"
                },
                {
                  "name": "server",
                  "key": "server",
                  "value": "Apache-Coyote/1.1",
                  "description": "A name for the server"
                },
                {
                  "name": "transfer-encoding",
                  "key": "transfer-encoding",
                  "value": "chunked",
                  "description": "The form of encoding used to safely transfer the entity to the user. Currently defined methods are: chunked, compress, deflate, gzip, identity."
                },
                {
                  "name": "content-type",
                  "key": "content-type",
                  "value": "application/json;charset\u003dUTF-8"
                }
              ],
              "body": "{}",
              "status": "OK"
            }
          ],
          "name": "首页-数据概览"
        },
        {
          "request": {
            "method": "POST",
            "description": "",
            "header": [
              {
                "key": "Content-Type",
                "value": "application/json",
                "type": "text",
                "description": ""
              }
            ],
            "body": {
              "mode": "raw",
              "options": {
                "raw": {
                  "language": "json"
                }
              },
              "raw": ""
            },
            "url": {
              "path": [
                "homepage",
                "list",
                "order"
              ],
              "query": [],
              "host": "{{platform-web}}",
              "raw": "{{platform-web}}/homepage/list/order"
            }
          },
          "response": [
            {
              "originalRequest": {
                "method": "POST",
                "description": "",
                "header": [
                  {
                    "key": "Content-Type",
                    "value": "application/json",
                    "type": "text",
                    "description": ""
                  }
                ],
                "body": {
                  "mode": "raw",
                  "options": {
                    "raw": {
                      "language": "json"
                    }
                  },
                  "raw": ""
                },
                "url": {
                  "query": [],
                  "host": "{{platform-web}}"
                }
              },
              "_postman_previewlanguage": "json",
              "code": 200,
              "_postman_previewtype": "text",
              "responseTime": 74,
              "name": "首页-订单列表-Example",
              "header": [
                {
                  "name": "date",
                  "key": "date",
                  "value": "周五, 22 7月 202211:10:41 GMT",
                  "description": "The date and time that the message was sent"
                },
                {
                  "name": "server",
                  "key": "server",
                  "value": "Apache-Coyote/1.1",
                  "description": "A name for the server"
                },
                {
                  "name": "transfer-encoding",
                  "key": "transfer-encoding",
                  "value": "chunked",
                  "description": "The form of encoding used to safely transfer the entity to the user. Currently defined methods are: chunked, compress, deflate, gzip, identity."
                },
                {
                  "name": "content-type",
                  "key": "content-type",
                  "value": "application/json;charset\u003dUTF-8"
                }
              ],
              "body": "}",
              "status": "OK"
            }
          ],
          "name": "首页-订单列表"
        }
      ],
      "name": "首页概览",
      "description": "首页概览"
    }
  ],
  "info": {
    "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
    "name": "platform-web-20220722111041",
    "description": "exported at 2022-07-22 11:10:41"
  }
}
```

**Comment by XuYuanWang** [comment]
今天发现，俺也一样，一样的报错。导出的json文件也无法导入到postman中（导入时报错）。可以导出md文件。

**Comment by XuYuanWang** [comment]
`java.lang.Throwable: Write-unsafe context! Model changes are allowed from write-safe contexts only. Please ensure you're using invokeLater/invokeAndWait with a correct modality state (not "any"). See TransactionGuard documentation for details.
  current modality=ModalityState:{[com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog[dialog11,743,218,546x646,invalid,layout=java.awt.BorderLayout,APPLICATION_MODAL,title=Export Location,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog$DialogRootPane[,8,0,530x638,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]]}
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.openapi.application.TransactionGuardImpl.assertWriteSafeContext(TransactionGuardImpl.java:157)
	at com.intellij.openapi.vfs.newvfs.RefreshSessionImpl.<init>(RefreshSessionImpl.java:58)
	at com.intellij.openapi.vfs.newvfs.RefreshQueueImpl.createSession(RefreshQueueImpl.java:194)
	at com.intellij.openapi.fileChooser.tree.FileRefresher.launch(FileRefresher.java:142)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:223)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:121)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1070)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:702)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:439)
	at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1668)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1626)
	at com.intellij.openapi.fileChooser.ex.FileChooserDialogImpl.choose(FileChooserDialogImpl.java:121)
	at com.itangcent.idea.utils.IdeaFileChooserHelper$selectFile$3.invoke(IdeaFileChooserHelper.kt:58)
	at com.itangcent.idea.utils.IdeaFileChooserHelper$selectFile$3.invoke(IdeaFileChooserHelper.kt:13)
	at com.itangcent.intellij.context.ActionContext$runInSwingUI$1.run(ActionContext.kt:283)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
`

**Comment by tangcent** [comment]
> 而且我发现了端倪，就是一个controller中有**2个接口**，**我注释掉任何一个都可以导成功**，2个一起导出则提示**那个错误**
> 
> 这是那个controller中2个接口导出的 **Exported data** 如下：


很奇怪，这份数据手动通过postman导入是成功的。
<img width="802" alt="image" src="https://user-images.githubusercontent.com/17569144/180449402-47f64395-acf1-4e5e-8c10-cd45753dd716.png">


<img width="317" alt="image" src="https://user-images.githubusercontent.com/17569144/180449450-31a1ca6e-e123-400d-a543-01fd410026f9.png">

> [ERROR] [WLError] 1 attribute is invalid

我现在没办法重现这个问题。

**Comment by 314537485** [comment]
嗯 我也是直接拿那个导出的postman.json可以导入，所以比较迷茫不知哪里的问题了。

**Comment by tangcent** [comment]
这个问题有点迷。
我试着导出一个类中所有的10个API，失败了。
但我试着分别导出一个类中前5个API和后5个API，却成功了。
不过，目前发现不产生`Example`时失败概率很低。
So, 可以试试: [v2.4.3](https://github.com/tangcent/easy-yapi/releases/tag/v2.4.3)

**Comment by 314537485** [comment]
> 不过，目前发现不产生`Example`时失败概率很低。

> So, 可以试试: [v2.4.3](https://github.com/tangcent/easy-yapi/releases/tag/v2.4.3)

嗯 已经升级到[v2.4.3]版本了，目前去掉**build example**试了几次均成功了，谢谢！
