### ISSUE TITLE
error to export to yapi when delete api on yapi-server

### ISSUE THREAD

**Issue by watersoona** [tangcent/easy-yapi#8]
**Describe the bug**
export data errro

**To Reproduce**
选中我已更新的接口目录，导出到yapi。

**Expected behavior**
成功导入

**Screenshots**

[INFO]	No config [.yapi.config] be found
[INFO]	No config [.easy.api.config] be found
[INFO]	Start find apis...
[INFO]	Add new cart:http://yapi-web.yapi.10.76.95.124.xip.io/project/21/interface/api/cat_33
[ERROR]	error to cache api info,com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
	at com.intellij.openapi.project.IndexNotReadyException.create(IndexNotReadyException.java:77)
	at com.intellij.util.indexing.FileBasedIndexImpl.handleDumbMode(FileBasedIndexImpl.java:777)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:726)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:709)
	at com.intellij.psi.stubs.StubIndexImpl.doProcessStubs(StubIndexImpl.java:305)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:281)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:121)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:109)
	at com.intellij.psi.impl.java.stubs.index.JavaFullClassNameIndex.get(JavaFullClassNameIndex.java:47)
	at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.doFindClasses(JavaFileManagerImpl.java:88)
	at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.findClass(JavaFileManagerImpl.java:123)
	at com.intellij.psi.impl.PsiElementFinderImpl.findClass(PsiElementFinderImpl.java:38)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.doFindClass(JavaPsiFacadeImpl.java:116)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClass(JavaPsiFacadeImpl.java:93)
	at com.siyeh.ig.psiutils.ClassUtils.findClass(ClassUtils.java:99)
	at com.itangcent.intellij.psi.PsiClassUtils.findMethodFromFullName(PsiClassUtils.kt:37)
	at com.itangcent.idea.plugin.api.cache.CachedClassExporter.readApiFromCache(CachedClassExporter.kt:154)
	at com.itangcent.idea.plugin.api.cache.CachedClassExporter.access$readApiFromCache(CachedClassExporter.kt:22)
	at com.itangcent.idea.plugin.api.cache.CachedClassExporter$export$1$1.invoke(CachedClassExporter.kt:88)
	at com.itangcent.idea.plugin.api.cache.CachedClassExporter$export$1$1.invoke(CachedClassExporter.kt:22)
	at com.itangcent.intellij.context.ActionContext$runInReadUI$1.run(ActionContext.kt:271)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:53)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:974)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:53)
	at com.itangcent.intellij.context.ActionContext.runInReadUI(ActionContext.kt:268)
	at com.itangcent.idea.plugin.api.cache.CachedClassExporter$export$1.invoke(CachedClassExporter.kt:86)
	at com.itangcent.idea.plugin.api.cache.CachedClassExporter$export$1.invoke(CachedClassExporter.kt:22)
	at com.itangcent.intellij.context.ActionContext$runAsync$2.run(ActionContext.kt:158)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[INFO]	search api from:com.xxx.xyz.admin.controller.UserController
[INFO]	Add new cart:http://yapi-web.yapi.10.76.95.124.xip.io/project/21/interface/api/cat_34
[INFO]	Add new cart:http://yapi-web.yapi.10.76.95.124.xip.io/project/21/interface/api/cat_35
[INFO]	Add new cart:http://yapi-web.yapi.10.76.95.124.xip.io/project/21/interface/api/cat_36
[INFO]	Add new cart:http://yapi-web.yapi.10.76.95.124.xip.io/project/21/interface/api/cat_37
[INFO]	Apis exported completed

Process finished with exit code 0

**Desktop (please complete the following information):**
 - OS: [macos mojave]

**Additional context**
我删除了某一个文件夹后（目的是之前的类的注释写的不好，删除的时候删错了，也就是说，删掉了一个我并没更新的接口目录。）
但是再次尝试就ok了，应该不是bug，只是日志输出？

**Comment by tangcent** [comment]
- The IndexNotReadyException always thrown on accessing indices when they're not ready, in so-called dumb mode. 
 - For this error, just try again
