### ISSUE TITLE
[Bug]yapi 导出失败

### ISSUE THREAD

**Issue by bingfen** [tangcent/easy-yapi#819]
[ERROR]	Apis export failed
[TRACE]	javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:371)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:314)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:309)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:654)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:473)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:369)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:201)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1505)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1420)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.itangcent.http.ApacheHttpClient.call(ApacheHttpClient.kt:159)
	at com.itangcent.http.ApacheHttpRequest.call(ApacheHttpClient.kt:179)
	at com.itangcent.suv.http.ConfigurableHttpClientProvider$HttpRequestWrapper.call(ConfigurableHttpClientProvider.kt:225)
	at com.itangcent.idea.plugin.api.export.yapi.AbstractYapiApiHelper.getByApi(AbstractYapiApiHelper.kt:163)
	at com.itangcent.idea.plugin.api.export.yapi.AbstractYapiApiHelper.getProjectInfo(AbstractYapiApiHelper.kt:115)
	at com.itangcent.idea.plugin.api.export.yapi.AbstractYapiApiHelper.getProjectInfo(AbstractYapiApiHelper.kt:139)
	at com.itangcent.idea.plugin.api.export.yapi.YapiTokenCheckerSupport.checkToken(YapiTokenCheckerSupport.kt:14)
	at com.itangcent.idea.plugin.settings.helper.YapiSettingsHelper.checked(YapiSettingsHelper.kt:132)
	at com.itangcent.idea.plugin.settings.helper.YapiSettingsHelper.getPrivateToken(YapiSettingsHelper.kt:104)
	at com.itangcent.idea.plugin.api.export.yapi.AbstractYapiApiExporter.getTokenOfModule(AbstractYapiApiExporter.kt:56)
	at com.itangcent.idea.plugin.api.export.yapi.AbstractYapiApiExporter.getCartForResource(AbstractYapiApiExporter.kt:63)
	at com.itangcent.idea.plugin.api.export.yapi.AbstractYapiApiExporter.exportDoc(AbstractYapiApiExporter.kt:112)
	at com.itangcent.idea.plugin.api.export.suv.SuvApiExporter$YapiApiExporterAdapter.doExportDocs(SuvApiExporter.kt:485)
	at com.itangcent.idea.plugin.api.export.suv.SuvApiExporter$ApiExporterAdapter$doExportApisFromMethod$1.invoke(SuvApiExporter.kt:335)
	at com.itangcent.idea.plugin.api.export.suv.SuvApiExporter$ApiExporterAdapter$doExportApisFromMethod$1.invoke(SuvApiExporter.kt:172)
	at com.itangcent.intellij.context.ActionContext$runAsync$2.run(ActionContext.kt:220)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by tangcent** [comment]
试试在`yapi server`填入`https://www.baidu.com`
导出看看会不会报`SSLHandshakeException`
