### ISSUE TITLE
[Bug] java.net.SocketTimeoutException: Read timed out

### ISSUE THREAD

**Issue by wowuhm** [tangcent/easy-yapi#864]
**Describe the bug**

idea导出postman每次都失败,原因超时,但是能导入成功,且有概率重复导出两次collection至Postman中

**To Reproduce**

导出Postman
   
**Logs**
- Logs of IDEA: <br>
```txt
run easy-yapi
[INFO]	Start find apis...
[TRACE]	No config be found
[DEBUG]	use recommend config
[INFO]	search api from: com.kiwi.platform.controller.oauth.OauthResourceController
[INFO]	PrivateToken of postman be found
[ERROR]	Post to https://api.getpostman.com/collections failed
[TRACE]	java.net.SocketTimeoutException: Read timed out
	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
	at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70)
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1374)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:985)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.itangcent.http.ApacheHttpClient.call(ApacheHttpClient.kt:159)
	at com.itangcent.http.ApacheHttpRequest.call(ApacheHttpClient.kt:179)
	at com.itangcent.suv.http.ConfigurableHttpClientProvider$HttpRequestWrapper.call(ConfigurableHttpClientProvider.kt:225)
	at com.itangcent.idea.plugin.api.export.postman.DefaultPostmanApiHelper.call(DefaultPostmanApiHelper.kt:429)
	at com.itangcent.idea.plugin.api.export.postman.DefaultPostmanApiHelper.doUpdateCollection(DefaultPostmanApiHelper.kt:215)
	at com.itangcent.idea.plugin.api.export.postman.DefaultPostmanApiHelper.updateCollection(DefaultPostmanApiHelper.kt:154)
	at com.itangcent.idea.plugin.api.export.postman.PostmanCachedApiHelper.updateCollection(PostmanCachedApiHelper.kt:76)
	at com.itangcent.idea.plugin.api.export.postman.PostmanApiExporter.updateRequestsToCollection(PostmanApiExporter.kt:178)
	at com.itangcent.idea.plugin.api.export.postman.PostmanApiExporter.updateRequestsToPostman(PostmanApiExporter.kt:168)
	at com.itangcent.idea.plugin.api.export.postman.PostmanApiExporter.export(PostmanApiExporter.kt:100)
	at com.itangcent.idea.plugin.api.export.postman.PostmanApiExporter.export(PostmanApiExporter.kt:54)
	at com.itangcent.idea.plugin.actions.PostmanExportAction.actionPerformed(PostmanExportAction.kt:51)
	at com.itangcent.intellij.actions.KotlinAnAction$actionPerformed$2.invoke(KotlinAnAction.kt:49)
	at com.itangcent.intellij.actions.KotlinAnAction$actionPerformed$2.invoke(KotlinAnAction.kt:18)
	at com.itangcent.intellij.context.ActionContext$runAsync$2.run(ActionContext.kt:220)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

[INFO]	try fix collection.....

```

**Comment by wowuhm** [comment]
是不是哪里调整一下读取超时时间就可以解决问题,国内连postman比较卡

**Comment by tangcent** [comment]
在<kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd> > <kbd>Http</kbd>里把`timeOut`设大一点

**Comment by wowuhm** [comment]
居然一直没往下拉过QAQ,谢谢
