### ISSUE TITLE
javax.validation分组能力支持问题

### ISSUE THREAD

**Issue by LiPeiKing** [tangcent/easy-yapi#892]
1、插件版本：2.5.1.191.0，IDEA版本：2021.3.3
2、移除勾选javax.validation, 勾选javax.validation(grouped)
3、代码定义
入参：
```
@Data
public class UserDTO {

    /**
     * 用户名
     */
    @NotBlank(groups = {GetValidator.class})
    private String username;

    /**
     * 密码
     */
    private String password;
}
```
GetValidator:
```
public interface GetValidator extends Default {
}
```
方法：
```
    /**
     * 添加
     * @param user 参数   {@link UserDTO}
     * @return 返回结果 {@link R<String>>}
     */
    @GetMapping("/get")
    public R<String> addUser(@Validated(value = GetValidator.class) UserDTO user) {
        return R.SUCCESS("删除成功！");
    }
```
3、上传接口报错
```
[ERROR]	error eval script:
def annMaps = it.annMaps("javax.validation.constraints.NotBlank")
groovy:
for(annMap in annMaps){
def fieldGroups = annMap["groups"] ?: [helper.findClass("javax.validation.groups.Default")]
def paramGroups = session.get("json-group") ?: [helper.findClass("javax.validation.groups.Default")]
for(fieldGroup in fieldGroups){
for(paramGroup in paramGroups){
if(fieldGroup.isExtend(paramGroup.name())){
return true
}
}
}
}
return false
[TRACE]	javax.script.ScriptException: javax.script.ScriptException: groovy.lang.MissingMethodException: No signature of method: com.intellij.psi.impl.source.PsiClassImpl.isExtend() is applicable for argument types: (String) values: [com.sitech.bds.portal.entity.GetValidator]
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:158)
	at com.itangcent.idea.plugin.rule.ScriptRuleParser.eval(ScriptRuleParser.kt:99)
	at com.itangcent.idea.plugin.rule.ScriptRuleParser.access$eval(ScriptRuleParser.kt:36)
	at com.itangcent.idea.plugin.rule.ScriptRuleParser$parseBooleanRule$1.invoke(ScriptRuleParser.kt:67)
	at com.itangcent.idea.plugin.rule.ScriptRuleParser$parseBooleanRule$1.invoke(ScriptRuleParser.kt:36)
	at com.itangcent.intellij.config.rule.BooleanRule$Companion$of$2.compute(BooleanRule.kt:36)
	at com.itangcent.intellij.config.rule.BooleanRule$Companion$of$2.compute(BooleanRule.kt:34)
	at com.itangcent.intellij.config.rule.BooleanRule$filterWith$1.invoke(BooleanRule.kt:17)
	at com.itangcent.intellij.config.rule.BooleanRule$filterWith$1.invoke(BooleanRule.kt:5)
	at com.itangcent.intellij.config.rule.BooleanRule$Companion$of$2.compute(BooleanRule.kt:36)
	at com.itangcent.intellij.config.rule.BooleanRule$Companion$of$2.compute(BooleanRule.kt:34)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer$RuleChainImpl.compute(DefaultRuleComputer.kt:74)
	at com.itangcent.intellij.config.rule.BooleanRuleMode$ANY$compute$1.apply(RuleMode.kt:55)
	at com.itangcent.intellij.config.rule.BooleanRuleMode$ANY$compute$1.apply(RuleMode.kt:51)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:528)
	at com.itangcent.intellij.config.rule.BooleanRuleMode$ANY.compute(RuleMode.kt:56)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer.doComputer(DefaultRuleComputer.kt:55)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer$computer$1.invoke(DefaultRuleComputer.kt:31)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer$computer$1.invoke(DefaultRuleComputer.kt:10)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry.computerListener(RuleComputeListenerRegistry.kt:34)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry.access$computerListener(RuleComputeListenerRegistry.kt:11)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry$computerListener$1.invoke(RuleComputeListenerRegistry.kt:31)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry$computerListener$1.invoke(RuleComputeListenerRegistry.kt:11)
	at com.itangcent.idea.utils.ContextualPsiClassHelper$InnerComputeListener.computer(ContextualPsiClassHelper.kt:246)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry.computerListener(RuleComputeListenerRegistry.kt:30)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry.computer(RuleComputeListenerRegistry.kt:24)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer.computer(DefaultRuleComputer.kt:29)
	at com.itangcent.intellij.config.rule.RuleComputer$DefaultImpls.computer(RuleComputer.kt:16)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer.computer(DefaultRuleComputer.kt:10)
	at com.itangcent.intellij.config.rule.RuleComputerKt.computer(RuleComputer.kt:27)
	at com.itangcent.idea.utils.CustomizedPsiClassHelper.afterParseFieldOrMethod(CustomizedPsiClassHelper.kt:45)
	at com.itangcent.idea.plugin.api.export.yapi.YapiPsiClassHelper.afterParseFieldOrMethod(YapiPsiClassHelper.kt:84)
	at com.itangcent.intellij.psi.AbstractPsiClassHelper$doGetFields$2.invoke(AbstractPsiClassHelper.kt:589)
	at com.itangcent.intellij.psi.AbstractPsiClassHelper$doGetFields$2.invoke(AbstractPsiClassHelper.kt:31)
	at com.itangcent.intellij.psi.AbstractPsiClassHelper.foreachField(AbstractPsiClassHelper.kt:628)
	at com.itangcent.intellij.psi.AbstractPsiClassHelper.doGetFields(AbstractPsiClassHelper.kt:569)
	at com.itangcent.intellij.psi.AbstractPsiClassHelper.doGetTypeObject(AbstractPsiClassHelper.kt:525)
	at com.itangcent.intellij.psi.DefaultPsiClassHelper.doGetTypeObject(DefaultPsiClassHelper.kt:234)
	at com.itangcent.intellij.psi.AbstractPsiClassHelper.doGetTypeObject(AbstractPsiClassHelper.kt:286)
	at com.itangcent.intellij.psi.AbstractPsiClassHelper.getTypeObject(AbstractPsiClassHelper.kt:138)
	at com.itangcent.idea.plugin.api.export.core.RequestClassExporter$raw$1.invoke(RequestClassExporter.kt:849)
	at com.itangcent.common.utils.ExtensibleKt.cache(Extensible.kt:97)
	at com.itangcent.idea.plugin.api.export.core.RequestClassExporter.raw(RequestClassExporter.kt:847)
	at com.itangcent.idea.plugin.api.export.core.RequestClassExporter.processMethodParameters(RequestClassExporter.kt:503)
	at com.itangcent.idea.plugin.api.export.core.RequestClassExporter.exportMethodApi(RequestClassExporter.kt:195)
	at com.itangcent.idea.plugin.api.export.core.RequestClassExporter.access$exportMethodApi(RequestClassExporter.kt:46)
	at com.itangcent.idea.plugin.api.export.core.RequestClassExporter$doExport$1$1.invoke(RequestClassExporter.kt:150)
	at com.itangcent.idea.plugin.api.export.core.RequestClassExporter$doExport$1$1.invoke(RequestClassExporter.kt:46)
	at com.itangcent.idea.plugin.api.ClassApiExporterHelper$foreachMethod$1$1$1.invoke(ClassApiExporterHelper.kt:151)
	at com.itangcent.idea.plugin.api.ClassApiExporterHelper$foreachMethod$1$1$1.invoke(ClassApiExporterHelper.kt:32)
	at com.itangcent.intellij.context.ActionContext$callInReadUI$1$1.invoke(ActionContext.kt:462)
	at com.itangcent.common.concurrent.ValueHolder.compute(Holder.kt:100)
	at com.itangcent.intellij.context.ActionContext$callInReadUI$1.run(ActionContext.kt:460)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:52)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:865)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:51)
	at com.itangcent.intellij.context.ActionContext.callInReadUI(ActionContext.kt:453)
	at com.itangcent.idea.plugin.api.ClassApiExporterHelper$foreachMethod$1$1.invoke(ClassApiExporterHelper.kt:150)
	at com.itangcent.idea.plugin.api.ClassApiExporterHelper$foreachMethod$1$1.invoke(ClassApiExporterHelper.kt:32)
	at com.itangcent.intellij.context.ActionContext$runAsync$2.run(ActionContext.kt:221)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: javax.script.ScriptException: groovy.lang.MissingMethodException: No signature of method: com.intellij.psi.impl.source.PsiClassImpl.isExtend() is applicable for argument types: (String) values: [com.sitech.bds.portal.entity.GetValidator]
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:320)
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:155)
	... 74 more
Caused by: groovy.lang.MissingMethodException: No signature of method: com.intellij.psi.impl.source.PsiClassImpl.isExtend() is applicable for argument types: (String) values: [com.sitech.bds.portal.entity.GetValidator]
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:70)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:46)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
	at Script412.run(Script412.groovy:9)
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:317)
	... 75 more

```

**Comment by tangcent** [comment]
@LiPeiKing 你先试试把
`@NotBlank(groups = {GetValidator.class})` 改成 `@NotBlank(groups = GetValidator.class)`

**Comment by LiPeiKing** [comment]
单个分组可以成功，但是若是一个字段有多个分组如何配置？
```
@NotBlank(groups = {GetValidator.class, AddValidator.class})
```
这种依然报错？
```
run easy-yapi
[INFO]	Start find apis...
[TRACE]	No config be found
[DEBUG]	use recommend config
[INFO]	search api from: com.sitech.bds.portal.controller.GebVisitController
[TRACE]	No config be found
[DEBUG]	use recommend config
[TRACE]	No config be found
[DEBUG]	use recommend config
[INFO]	search api from: com.sitech.bds.portal.controller.GebVisitController
[ERROR]	error eval script:
def annMaps = it.annMaps("javax.validation.constraints.NotBlank")
groovy:
for(annMap in annMaps){
def fieldGroups = annMap["groups"] ?: [helper.findClass("javax.validation.groups.Default")]
def paramGroups = session.get("json-group") ?: [helper.findClass("javax.validation.groups.Default")]
for(fieldGroup in fieldGroups){
for(paramGroup in paramGroups){
if(fieldGroup.isExtend(paramGroup.name())){
return true
}
}
}
}
return false
[TRACE]	javax.script.ScriptException: javax.script.ScriptException: groovy.lang.MissingMethodException: No signature of method: com.intellij.psi.impl.source.PsiClassImpl.isExtend() is applicable for argument types: (String) values: [com.sitech.bds.portal.entity.GetValidator]
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:158)
	at com.itangcent.idea.plugin.rule.ScriptRuleParser.eval(ScriptRuleParser.kt:99)
	at com.itangcent.idea.plugin.rule.ScriptRuleParser.access$eval(ScriptRuleParser.kt:36)
	at com.itangcent.idea.plugin.rule.ScriptRuleParser$parseBooleanRule$1.invoke(ScriptRuleParser.kt:67)
	at com.itangcent.idea.plugin.rule.ScriptRuleParser$parseBooleanRule$1.invoke(ScriptRuleParser.kt:36)
	at com.itangcent.intellij.config.rule.BooleanRule$Companion$of$2.compute(BooleanRule.kt:36)
	at com.itangcent.intellij.config.rule.BooleanRule$Companion$of$2.compute(BooleanRule.kt:34)
	at com.itangcent.intellij.config.rule.BooleanRule$filterWith$1.invoke(BooleanRule.kt:17)
	at com.itangcent.intellij.config.rule.BooleanRule$filterWith$1.invoke(BooleanRule.kt:5)
	at com.itangcent.intellij.config.rule.BooleanRule$Companion$of$2.compute(BooleanRule.kt:36)
	at com.itangcent.intellij.config.rule.BooleanRule$Companion$of$2.compute(BooleanRule.kt:34)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer$RuleChainImpl.compute(DefaultRuleComputer.kt:74)
	at com.itangcent.intellij.config.rule.BooleanRuleMode$ANY$compute$1.apply(RuleMode.kt:55)
	at com.itangcent.intellij.config.rule.BooleanRuleMode$ANY$compute$1.apply(RuleMode.kt:51)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:528)
	at com.itangcent.intellij.config.rule.BooleanRuleMode$ANY.compute(RuleMode.kt:56)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer.doComputer(DefaultRuleComputer.kt:55)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer$computer$1.invoke(DefaultRuleComputer.kt:31)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer$computer$1.invoke(DefaultRuleComputer.kt:10)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry.computerListener(RuleComputeListenerRegistry.kt:34)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry.access$computerListener(RuleComputeListenerRegistry.kt:11)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry$computerListener$1.invoke(RuleComputeListenerRegistry.kt:31)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry$computerListener$1.invoke(RuleComputeListenerRegistry.kt:11)
	at com.itangcent.idea.utils.ContextualPsiClassHelper$InnerComputeListener.computer(ContextualPsiClassHelper.kt:246)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry.computerListener(RuleComputeListenerRegistry.kt:30)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry.computer(RuleComputeListenerRegistry.kt:24)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer.computer(DefaultRuleComputer.kt:29)
	at com.itangcent.intellij.config.rule.RuleComputer$DefaultImpls.computer(RuleComputer.kt:16)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer.computer(DefaultRuleComputer.kt:10)
	at com.itangcent.intellij.config.rule.RuleComputerKt.computer(RuleComputer.kt:27)
	at com.itangcent.idea.utils.CustomizedPsiClassHelper.afterParseFieldOrMethod(CustomizedPsiClassHelper.kt:45)
	at com.itangcent.idea.plugin.api.export.yapi.YapiPsiClassHelper.afterParseFieldOrMethod(YapiPsiClassHelper.kt:84)
	at com.itangcent.intellij.psi.AbstractPsiClassHelper$doGetFields$2.invoke(AbstractPsiClassHelper.kt:589)
	at com.itangcent.intellij.psi.AbstractPsiClassHelper$doGetFields$2.invoke(AbstractPsiClassHelper.kt:31)
	at com.itangcent.intellij.psi.AbstractPsiClassHelper.foreachField(AbstractPsiClassHelper.kt:628)
	at com.itangcent.intellij.psi.AbstractPsiClassHelper.doGetFields(AbstractPsiClassHelper.kt:569)
	at com.itangcent.intellij.psi.AbstractPsiClassHelper.doGetTypeObject(AbstractPsiClassHelper.kt:525)
	at com.itangcent.intellij.psi.DefaultPsiClassHelper.doGetTypeObject(DefaultPsiClassHelper.kt:234)
	at com.itangcent.intellij.psi.AbstractPsiClassHelper.doGetTypeObject(AbstractPsiClassHelper.kt:286)
	at com.itangcent.intellij.psi.AbstractPsiClassHelper.getTypeObject(AbstractPsiClassHelper.kt:138)
	at com.itangcent.idea.plugin.api.export.core.RequestClassExporter$raw$1.invoke(RequestClassExporter.kt:849)
	at com.itangcent.common.utils.ExtensibleKt.cache(Extensible.kt:97)
	at com.itangcent.idea.plugin.api.export.core.RequestClassExporter.raw(RequestClassExporter.kt:847)
	at com.itangcent.idea.plugin.api.export.core.RequestClassExporter.processMethodParameters(RequestClassExporter.kt:503)
	at com.itangcent.idea.plugin.api.export.core.RequestClassExporter.exportMethodApi(RequestClassExporter.kt:195)
	at com.itangcent.idea.plugin.api.export.core.RequestClassExporter.access$exportMethodApi(RequestClassExporter.kt:46)
	at com.itangcent.idea.plugin.api.export.core.RequestClassExporter$doExport$1$1.invoke(RequestClassExporter.kt:150)
	at com.itangcent.idea.plugin.api.export.core.RequestClassExporter$doExport$1$1.invoke(RequestClassExporter.kt:46)
	at com.itangcent.idea.plugin.api.ClassApiExporterHelper$foreachMethod$1$1$1.invoke(ClassApiExporterHelper.kt:151)
	at com.itangcent.idea.plugin.api.ClassApiExporterHelper$foreachMethod$1$1$1.invoke(ClassApiExporterHelper.kt:32)
	at com.itangcent.intellij.context.ActionContext$callInReadUI$1$1.invoke(ActionContext.kt:462)
	at com.itangcent.common.concurrent.ValueHolder.compute(Holder.kt:100)
	at com.itangcent.intellij.context.ActionContext$callInReadUI$1.run(ActionContext.kt:460)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:52)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:865)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:51)
	at com.itangcent.intellij.context.ActionContext.callInReadUI(ActionContext.kt:453)
	at com.itangcent.idea.plugin.api.ClassApiExporterHelper$foreachMethod$1$1.invoke(ClassApiExporterHelper.kt:150)
	at com.itangcent.idea.plugin.api.ClassApiExporterHelper$foreachMethod$1$1.invoke(ClassApiExporterHelper.kt:32)
	at com.itangcent.intellij.context.ActionContext$runAsync$2.run(ActionContext.kt:221)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: javax.script.ScriptException: groovy.lang.MissingMethodException: No signature of method: com.intellij.psi.impl.source.PsiClassImpl.isExtend() is applicable for argument types: (String) values: [com.sitech.bds.portal.entity.GetValidator]
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:320)
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:155)
	... 74 more
Caused by: groovy.lang.MissingMethodException: No signature of method: com.intellij.psi.impl.source.PsiClassImpl.isExtend() is applicable for argument types: (String) values: [com.sitech.bds.portal.entity.GetValidator]
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:70)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:46)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
	at Script139.run(Script139.groovy:9)
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:317)
	... 75 more

[WARN]	error to resolve class:String>
```

**Comment by tangcent** [comment]
> 单个分组可以成功，但是若是一个字段有多个分组如何配置？

没办法通过配置解决。
等我修复

**Comment by LiPeiKing** [comment]
请问下个版本中会包含么？

**Comment by tangcent** [comment]
patch with #893: [easy-yapi-2.5.1.191.0.zip](https://github.com/tangcent/easy-yapi/files/10308627/easy-yapi-2.5.1.191.0.zip)

**Comment by LiPeiKing** [comment]
大佬效率！
