### ISSUE TITLE
[Question] 同一个接口，能上传到多个不同的项目和分类下吗

### ISSUE THREAD

**Issue by OuLeBe** [tangcent/easy-yapi#939]
你好，我们有很多接口是很多功能模块都有重用的，我们的接口管理是按功能场景建不同的项目，这就导致这些重用的接口不能同步到每个项目里，想问问怎么样能做到同一个接口，能上传到多个不同的项目和分类下呢

**Comment by tangcent** [comment]
如何重用的? 项目结构大概是什么样的?

**Comment by OuLeBe** [comment]
项目说的是yapi的项目，我们想根据功能场景来在yapi建项目，方便前端查找对应的接口；
      目前知道module和folder注解可以把接口上传到指定的项目和分类里，但是只能传到一个项目分类里，我们想的是把接口上传到多个yapi项目里，这个目前有解决的方法吗？

**Comment by tangcent** [comment]
目前没有好的办法处理这种情况，你有什么好的想法吗?

**Comment by OuLeBe** [comment]
是否可扩展@folder 功能，类似@param 可以支持多个，注解后两个参数，第一个指定项目，第二个指定分类目录，这样每个folder注解就可以同步到不同的项目与分类中
```java
/**
* @folder 项目 分类目录
* @folder 项目 分类目录
* /
```

**Comment by tangcent** [comment]
[v2.5.6](https://github.com/tangcent/easy-yapi/releases/tag/v2.5.6)

``````

moduleSync=```
def moduleSync = ["user":["test2","test3"],"test":["test2","test3"],"springboot-demo":["test2","test3"]]
```

yapi.save.after=groovy:```
${moduleSync}
def module = runtime.module()
def syncList = moduleSync[module]
if(syncList==null){
    logger.info("$module not need sync")
    return
}
logger.info("start sync $module")
def apiId = yapiInfo["_id"]
def yapiApiHelper = runtime.getBean("com.itangcent.idea.plugin.api.export.yapi.YapiApiHelper")
runtime.async {
    for(syncmodule in syncList){
        logger.info("sync $module to $syncmodule")
        yapiApiHelper.copyApi(["module":module,"id":apiId],["module":syncmodule])
    }
}
```
``````

**Comment by OuLeBe** [comment]
能具体说一下应该怎么操作吗

**Comment by tangcent** [comment]
1.  去这里下[v2.5.6](https://github.com/tangcent/easy-yapi/releases/tag/v2.5.6)，手动安装
2.  去<kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd> > <kbd>BuiltInConfig</kbd> 或者 [配置文件](http://easyyapi.com/setting/local-file-config.html)里配置上面的信息
3. > def moduleSync = ["user":["test2","test3"]]

这里就是指user模块同步到"test2"和"test3"模块

4. module的概念看这里: http://easyyapi.com/setting/rules/module.html

**Comment by OuLeBe** [comment]
```java
def apiId = yapiInfo["_id"]
```
这行代码，获取不到apiId

**Comment by tangcent** [comment]
升到2.5.6.212.0了吗？

**Comment by OuLeBe** [comment]
已经更新了的

**Comment by tangcent** [comment]
> 已经更新了的

抱歉，我这边对yapi进行了一些魔改，所以我拿到的response和你们的有点偏差。
在修复之前你可以这样配置试试:

``````

moduleSync=```
def moduleSync = ["user":["test2","test3"],"test":["test2","test3"],"springboot-demo":["test2","test3"]]
```

yapi.save.after=groovy:```
${moduleSync}
def module = runtime.module()
def syncList = moduleSync[module]
if(syncList==null){
    logger.info("$module not need sync")
    return
}
logger.info("start sync $module")
logger.info("yapiInfo:\n"+yapiInfo)
def apiId = localStorage["apiId"]
logger.info("apiId:"+apiId)
def yapiApiHelper = runtime.getBean("com.itangcent.idea.plugin.api.export.yapi.YapiApiHelper")
localStorage.set("inSync",true)
for(syncmodule in syncList){
    logger.info("sync api $apiId in $module to $syncmodule")
    yapiApiHelper.copyApi(["module":module,"id":apiId],["module":syncmodule])
}
localStorage.remove("inSync")
```


http.call.after=groovy:```
if(localStorage.get("inSync") == null && response.request().url().endsWith("/api/interface/save")){
    def apiId = tool.parseJson(response.string()).data[0]._id.toString()
    logger.info("apiId->"+apiId)
    localStorage.set("apiId",apiId)
}
```
``````

**Comment by OuLeBe** [comment]
这个脚本还是拿不到apiId
`[ERROR]	error eval script:
def moduleSync = ["test":["test2","test3"],"springboot-demo":["test2","test3"]]
def module = runtime.module()
def syncList = module.split("\\s+")
logger.info("$syncList")
if(syncList==null){
logger.info("$module not need sync")
return
}
logger.info("start sync $module")
logger.info("id $apiId need sync")
logger.info("yapiInfo:\n"+yapiInfo)
def apiId = localStorage["apiId"]
logger.info("apiId:"+apiId)
def yapiApiHelper = runtime.getBean("com.itangcent.idea.plugin.api.export.yapi.YapiApiHelper")
for(syncmodule in syncList){
logger.info("sync $module to $syncmodule")
if(syncmodule != module){
yapiApiHelper.copyApi(["module":module,"id":apiId],["module":syncmodule])
}
}
localStorage.remove("inSync")
[TRACE]	javax.script.ScriptException: javax.script.ScriptException: groovy.lang.MissingPropertyException: No such property: apiId for class: Script552
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:158)
	at com.itangcent.idea.plugin.rule.ScriptRuleParser.eval(ScriptRuleParser.kt:97)
	at com.itangcent.idea.plugin.rule.ScriptRuleParser.access$eval(ScriptRuleParser.kt:34)
	at com.itangcent.idea.plugin.rule.ScriptRuleParser$parseEventRule$1.invoke(ScriptRuleParser.kt:77)
	at com.itangcent.idea.plugin.rule.ScriptRuleParser$parseEventRule$1.invoke(ScriptRuleParser.kt:76)
	at com.itangcent.intellij.config.rule.EventRule$Companion$of$1.compute(EventRule.kt:16)
	at com.itangcent.intellij.config.rule.EventRule$Companion$of$1.compute(EventRule.kt:14)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer$RuleChainImpl.compute(DefaultRuleComputer.kt:74)
	at com.itangcent.intellij.config.rule.EventRuleMode$THROW_IN_ERROR.compute(RuleMode.kt:88)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer.doComputer(DefaultRuleComputer.kt:55)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer$computer$1.invoke(DefaultRuleComputer.kt:31)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer$computer$1.invoke(DefaultRuleComputer.kt:29)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry.computerListener(RuleComputeListenerRegistry.kt:34)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry.access$computerListener(RuleComputeListenerRegistry.kt:10)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry$computerListener$1.invoke(RuleComputeListenerRegistry.kt:31)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry$computerListener$1.invoke(RuleComputeListenerRegistry.kt:30)
	at com.itangcent.idea.utils.ContextualPsiClassHelper$InnerComputeListener.computer(ContextualPsiClassHelper.kt:251)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry.computerListener(RuleComputeListenerRegistry.kt:30)
	at com.itangcent.idea.utils.RuleComputeListenerRegistry.computer(RuleComputeListenerRegistry.kt:24)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer.computer(DefaultRuleComputer.kt:29)
	at com.itangcent.intellij.config.rule.RuleComputer$DefaultImpls.computer(RuleComputer.kt:16)
	at com.itangcent.intellij.config.rule.DefaultRuleComputer.computer(DefaultRuleComputer.kt:9)
	at com.itangcent.idea.plugin.api.export.yapi.AbstractYapiApiExporter.exportDoc(AbstractYapiApiExporter.kt:113)
	at com.itangcent.idea.plugin.api.export.yapi.YapiApiExporter.exportDoc(YapiApiExporter.kt:63)
	at com.itangcent.idea.plugin.api.export.yapi.AbstractYapiApiExporter.exportDoc(AbstractYapiApiExporter.kt:91)
	at com.itangcent.idea.plugin.api.export.yapi.YapiApiExporter$doExport$1.invoke(YapiApiExporter.kt:36)
	at com.itangcent.idea.plugin.api.export.yapi.YapiApiExporter$doExport$1.invoke(YapiApiExporter.kt:34)
	at com.itangcent.idea.plugin.api.ClassApiExporterHelper$export$3$1.invoke(ClassApiExporterHelper.kt:246)
	at com.itangcent.idea.plugin.api.ClassApiExporterHelper$export$3$1.invoke(ClassApiExporterHelper.kt:246)
	at com.itangcent.idea.plugin.api.export.core.RequestClassExporter.exportMethodApi(RequestClassExporter.kt:203)
	at com.itangcent.idea.plugin.api.export.core.RequestClassExporter.access$exportMethodApi(RequestClassExporter.kt:45)
	at com.itangcent.idea.plugin.api.export.core.RequestClassExporter$doExport$1$1.invoke(RequestClassExporter.kt:150)
	at com.itangcent.idea.plugin.api.export.core.RequestClassExporter$doExport$1$1.invoke(RequestClassExporter.kt:142)
	at com.itangcent.idea.plugin.api.ClassApiExporterHelper$foreachMethod$1$1$1.invoke(ClassApiExporterHelper.kt:151)
	at com.itangcent.idea.plugin.api.ClassApiExporterHelper$foreachMethod$1$1$1.invoke(ClassApiExporterHelper.kt:150)
	at com.itangcent.intellij.context.ActionContext$callInReadUI$1$1.invoke(ActionContext.kt:462)
	at com.itangcent.common.concurrent.ValueHolder.compute(Holder.kt:100)
	at com.itangcent.intellij.context.ActionContext.callInReadUI$lambda$15(ActionContext.kt:460)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:60)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:891)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:69)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:59)
	at com.itangcent.intellij.context.ActionContext.callInReadUI(ActionContext.kt:453)
	at com.itangcent.idea.plugin.api.ClassApiExporterHelper$foreachMethod$1$1.invoke(ClassApiExporterHelper.kt:150)
	at com.itangcent.idea.plugin.api.ClassApiExporterHelper$foreachMethod$1$1.invoke(ClassApiExporterHelper.kt:146)
	at com.itangcent.intellij.context.ActionContext.runAsync$lambda$8(ActionContext.kt:221)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: javax.script.ScriptException: groovy.lang.MissingPropertyException: No such property: apiId for class: Script552
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:320)
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:155)
	... 50 more
Caused by: groovy.lang.MissingPropertyException: No such property: apiId for class: Script552
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:65)
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:341)
	at Script552.run(Script552.groovy:11)
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:317)
	... 51 more
`

**Comment by tangcent** [comment]
> logger.info("id $apiId need sync")

你加的这个得放在`def apiId = localStorage["apiId"]`后面

**Comment by OuLeBe** [comment]
我修改后的脚本：
```
def moduleSync = ["接口规范":["test-1 test分类"],"springboot-demo":["test2","test3"]]
```
实现模块 接口规范的接口，复制到模块test-1的test分类下，如果不指定分类，就按原接口分类
但是有个问题是，如果模块test-1一开始没有配置token，不会弹窗要求输入token，这个目前不知道怎么处理

``` java
http.call.before=groovy:```
logger.info("call:"+request.url()+" body:"+request.body())
if(localStorage.get("inSync") == null && request.url().endsWith("/api/interface/add_cat")){
     
      logger.info("token->"+request.body()["token"])
      localStorage.set("token",request.body()["token"])
    
  }
```

http.call.after=groovy:```
  logger.info("response:"+response.string())
  if(localStorage.get("inSync") == null && response.request().url().endsWith("/api/interface/save")){
    def resData = tool.parseJson(response.string()).data;
    if(resData.size() >0){
      def apiId = resData[0]._id.toString()
      logger.info("apiId->"+apiId)
      localStorage.set("apiId",apiId)
    }
  }
```

moduleSync=```
    def moduleSync = ["接口规范":["test-1 test分类"],"springboot-demo":["test2","test3"]]
```
yapi.save.after=groovy:```
    ${moduleSync}
    def module = runtime.module()
    def syncList = moduleSync[module]
    logger.info("$syncList")
    if(syncList==null){
        logger.info("$module not need sync")
        return
    }
    logger.info("start sync $module")  
    def apiId = localStorage["apiId"] 
    def token = localStorage["token"] 
    logger.info("apiId:"+apiId)
    def yapiApiHelper = runtime.getBean("com.itangcent.idea.plugin.api.export.yapi.YapiApiHelper")
	for(syncmodule in syncList){ 
		def groups = syncmodule.split("\\s+");
		def carId = null;
		if(groups.size() == 2){
		try{
			 def cartWeb = yapiApiHelper.findCartWeb(groups[0],groups[1])
			 if(cartWeb == null && token != null)
			 {
				yapiApiHelper.addCart(token,groups[1],groups[1])
				cartWeb = yapiApiHelper.findCartWeb(groups[0],groups[1])
			 }
			 if(cartWeb !=null){
				logger.info("cartweb $cartWeb")
			   carId = regex.getGroup0(/(?<=cat_)\d+/,cartWeb)
			 }
		}catch(Exception e){}
		}
		logger.info("sync $module to $syncmodule")
		if(syncmodule != module){
			yapiApiHelper.copyApi(["module":module,"id":apiId],["module":groups[0],"catId":carId])
		}
	}
    localStorage.remove("inSync")
```
```

**Comment by OuLeBe** [comment]
我修改后的脚本：
```
def moduleSync = ["接口规范":["test-1 test分类"],"springboot-demo":["test2","test3"]]
```
实现模块 接口规范的接口，复制到模块test-1的test分类下，如果不指定分类，就按原接口分类
但是有个问题是，如果模块test-1一开始没有配置token，不会弹窗要求输入token，这个目前不知道怎么处理

``` java
http.call.before=groovy:```
logger.info("call:"+request.url()+" body:"+request.body())
if(localStorage.get("inSync") == null && request.url().endsWith("/api/interface/add_cat")){
     
      logger.info("token->"+request.body()["token"])
      localStorage.set("token",request.body()["token"])
    
  }
```

http.call.after=groovy:```
  logger.info("response:"+response.string())
  if(localStorage.get("inSync") == null && response.request().url().endsWith("/api/interface/save")){
    def resData = tool.parseJson(response.string()).data;
    if(resData.size() >0){
      def apiId = resData[0]._id.toString()
      logger.info("apiId->"+apiId)
      localStorage.set("apiId",apiId)
    }
  }
```

moduleSync=```
    def moduleSync = ["接口规范":["test-1 test分类"],"springboot-demo":["test2","test3"]]
```
yapi.save.after=groovy:```
    ${moduleSync}
    def module = runtime.module()
    def syncList = moduleSync[module]
    logger.info("$syncList")
    if(syncList==null){
        logger.info("$module not need sync")
        return
    }
    logger.info("start sync $module")  
    def apiId = localStorage["apiId"] 
    def token = localStorage["token"] 
    logger.info("apiId:"+apiId)
    def yapiApiHelper = runtime.getBean("com.itangcent.idea.plugin.api.export.yapi.YapiApiHelper")
	for(syncmodule in syncList){ 
		def groups = syncmodule.split("\\s+");
		def carId = null;
		if(groups.size() == 2){
		try{
			 def cartWeb = yapiApiHelper.findCartWeb(groups[0],groups[1])
			 if(cartWeb == null && token != null)
			 {
				yapiApiHelper.addCart(token,groups[1],groups[1])
				cartWeb = yapiApiHelper.findCartWeb(groups[0],groups[1])
			 }
			 if(cartWeb !=null){
				logger.info("cartweb $cartWeb")
			   carId = regex.getGroup0(/(?<=cat_)\d+/,cartWeb)
			 }
		}catch(Exception e){}
		}
		logger.info("sync $module to $syncmodule")
		if(syncmodule != module){
			yapiApiHelper.copyApi(["module":module,"id":apiId],["module":groups[0],"catId":carId])
		}
	}
    localStorage.remove("inSync")
```
```

**Comment by OuLeBe** [comment]
还有个问题，我把 moduleSync定义从buildinconfig中移到项目下的配置文件.yapi.config中，出现脚本读取配置之后，中文变成了Unicode编码，而不是中文字符，导致配置没有匹配到了
```
 [INFO]	apiId->24694
[INFO]	moduleSync= [u63A5u53E3u89C4u8303:[test-1 testu5206u7C7B], springboot-demo:[test2, test3]]
[INFO]	null
[INFO]	接口规范 not need sync
```

**Comment by tangcent** [comment]
你这套逻辑看起来有点复杂，copyApi自动创建cart的逻辑不满足你的需求吗? 还是你那里自动创建cart的逻辑有问题?

> 如果模块test-1一开始没有配置token，不会弹窗要求输入token，这个目前不知道怎么处理

试试:
```
runtime.getBean("com.itangcent.idea.plugin.api.export.yapi.AbstractYapiApiHelper#getYapiSettingsHelper").getPrivateToken(module, false)
```

> 我把 moduleSync定义从buildinconfig中移到项目下的配置文件.yapi.config中，出现脚本读取配置之后，中文变成了Unicode编码，而不是中文字符，导致配置没有匹配到了

确认一下`.yapi.config`是不是用的`UTF-8`编码?

**Comment by OuLeBe** [comment]
一般情况下，我这边把接口拷贝到其他项目时，接口所在的cart也是不同的，copyApi自动创建cart的逻辑，是根据是否传入cartid来指定接口所在的cart；
  这样导致我想把接口放到不同cart下面，就只能先查找是否已存在cart，不存在就先创建cart；
  如果你能增加判断通过cart的Name来自动创建cart，就满足我的需求了。

```groovy
runtime.getBean("com.itangcent.idea.plugin.api.export.yapi.AbstractYapiApiHelper#getYapiSettingsHelper").getPrivateToken(module, false)
```
这样写是不行的，getYapiSettingsHelper方法没有定义
```java
[TRACE]	javax.script.ScriptException: javax.script.ScriptException: java.lang.IllegalArgumentException: class com.itangcent.idea.plugin.api.export.yapi.AbstractYapiApiHelper#getYapiSettingsHelper not be found
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:158)
	at com.itangcent.idea.plugin.rule.ScriptRuleParser.eval(ScriptRuleParser.kt:97)
	at com.itangcent.idea.plugin.rule.ScriptRuleParser.access$eval(ScriptRuleParser.kt:34)
```

还有 `.yapi.config` 文件是utf-8编码的****

**Comment by tangcent** [comment]
> 这样写是不行的，getYapiSettingsHelper方法没有定义

我复制错了，是`com.itangcent.idea.plugin.settings.helper.YapiSettingsHelper`

> 还有 `.yapi.config` 文件是utf-8编码的****

IDEA右下角显示编码UTF-8吗?

**Comment by OuLeBe** [comment]
`IDEA右下角显示编码UTF-8吗?`
是的，idea显示是UTF-8
![image](https://user-images.githubusercontent.com/129053376/231331555-cf862e5f-aada-4d86-836b-c86bbc12077a.png)

**Comment by tangcent** [comment]
你的系统是windows吗?
试试修改<kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd> > <kbd>Common</kbd> > <kbd>charset</kbd> ，看看是不是console输出的问题

**Comment by OuLeBe** [comment]
我的是windows的，这样子设置之后，中文乱码，配置读出来还是unicode
![image](https://user-images.githubusercontent.com/129053376/231620497-d9ad3661-7343-487e-a7d4-1b50ecf379ee.png)
![image](https://user-images.githubusercontent.com/129053376/231620537-c46bddf5-4af8-4e0c-b7e1-2d80be632b4e.png)

**Comment by tangcent** [comment]
那就不是console输出的问题。
把你的配置文件上传一下？
就只要这一行的就行:
![image](https://user-images.githubusercontent.com/17569144/231624647-7998a8f1-c040-49b3-8206-395c41aa32e8.png)

**Comment by OuLeBe** [comment]
````
moduleSync=```
def moduleSync = ["接口规范":["test-1 test分类"],"springboot-demo":["test2","test3"]]
```
````

**Comment by tangcent** [comment]
> ```
> moduleSync=```
> def moduleSync = ["接口规范":["test-1 test分类"],"springboot-demo":["test2","test3"]]
> ```

我复制文本的话使用正常，你试试上传文件:
<img width="865" alt="image" src="https://user-images.githubusercontent.com/17569144/231661550-a6a7ac50-1cfc-4eaf-b8e4-2c974a793c37.png">

**Comment by OuLeBe** [comment]
[yapi.config.zip](https://github.com/tangcent/easy-yapi/files/11218484/yapi.config.zip)

**Comment by tangcent** [comment]
我试了一下，你这个文件内容是GBK编码的。

[temp.zip](https://github.com/tangcent/easy-yapi/files/11218594/temp.zip)

**Comment by OuLeBe** [comment]
你是对的，重新换成utf-8的文件，就可以了
