### ISSUE TITLE
IDEA 导出到 YAPI 正常但是执行过程报错误 failed load remote config，麻烦作者指点一二

### ISSUE THREAD

**Issue by chenshuaijieo** [tangcent/easy-yapi#942]
run easy-yapi
[TRACE]	No config be found
[DEBUG]	use recommend config
[DEBUG]	use built-in config
[ERROR]	failed load remote config
[TRACE]	java.io.FileNotFoundException: / (Is a directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at com.itangcent.intellij.config.resource.FileResource.getInputStream(FileResource.kt:42)
	at com.itangcent.intellij.config.resource.Resource.getBytes(Resource.kt:21)
	at com.itangcent.idea.plugin.settings.helper.RemoteConfigSettingsHelper.refreshConfig(RemoteConfigSettingsHelper.kt:49)
	at com.itangcent.idea.plugin.settings.helper.RemoteConfigSettingsHelper.loadConfig(RemoteConfigSettingsHelper.kt:44)
	at com.itangcent.idea.plugin.settings.helper.RemoteConfigSettingsHelper$remoteConfigContent$3.invoke(RemoteConfigSettingsHelper.kt:40)
	at com.itangcent.idea.plugin.settings.helper.RemoteConfigSettingsHelper$remoteConfigContent$3.invoke(RemoteConfigSettingsHelper.kt:40)
	at kotlin.text.StringsKt__AppendableKt.appendElement(Appendable.kt:85)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:3490)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt:3507)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:3506)
	at com.itangcent.idea.plugin.settings.helper.RemoteConfigSettingsHelper.remoteConfigContent(RemoteConfigSettingsHelper.kt:40)
	at com.itangcent.idea.plugin.config.RecommendConfigReader.tryLoadRemote(RecommendConfigReader.kt:189)
	at com.itangcent.idea.plugin.config.RecommendConfigReader.initDelegateAndRecommend(RecommendConfigReader.kt:135)
	at com.itangcent.idea.plugin.config.RecommendConfigReader.checkStatus(RecommendConfigReader.kt:79)
	at com.itangcent.idea.plugin.config.RecommendConfigReader.first(RecommendConfigReader.kt:53)
	at com.itangcent.idea.plugin.settings.helper.YapiSettingsHelper.getServer(YapiSettingsHelper.kt:54)
	at com.itangcent.idea.plugin.api.export.yapi.YapiApiExporter.export(YapiApiExporter.kt:26)
	at com.itangcent.idea.plugin.actions.YapiExportAction.actionPerformed(YapiExportAction.kt:57)
	at com.itangcent.intellij.actions.KotlinAnAction$actionPerformed$2.invoke(KotlinAnAction.kt:49)
	at com.itangcent.intellij.actions.KotlinAnAction$actionPerformed$2.invoke(KotlinAnAction.kt:47)
	at com.itangcent.intellij.context.ActionContext.runAsync$lambda$8(ActionContext.kt:221)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by tangcent** [comment]
1.  排查一下<kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd> > <kbd>Remote</kbd> 中有没有填入无效的地址
2. 清理一下缓存: <kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd> > <kbd>Cache</kbd>

**Comment by chenshuaijieo** [comment]
已解决，感谢作者
