### ISSUE TITLE
[Bug] 貌似最新版idea导出卡死

### ISSUE THREAD

**Issue by yanye666** [tangcent/easy-yapi#946]
**Describe the bug**

貌似最新版idea导出卡死

**To Reproduce**

使用作者提供的spring-demo，
![image](https://user-images.githubusercontent.com/42414099/230550424-3d897617-2c07-4936-b075-90edba86abd6.png)
导出当前类，
![image](https://user-images.githubusercontent.com/42414099/230550193-789ac689-6b3d-4bdb-82cb-3d2d153bb428.png)
卡死
日志上没什么输出内容额；

**Expected behavior**

**Screenshots**

1. Add config:
   
   ```properties
   http.call.before=groovy:logger.info("call:"+request.url())
   http.call.after=groovy:logger.info("response:"+response.string())
   api.class.parse.before=groovy:logger.info("[api] before parse class:"+it)
   api.class.parse.after=groovy:logger.info("[api] after parse class:"+it)
   api.method.parse.before=groovy:logger.info("[api] before parse method:"+it)
   api.method.parse.after=groovy:logger.info("[api] after parse method:"+it)
   api.param.parse.before=groovy:logger.info("[api] before parse param:"+it)
   api.param.parse.after=groovy:logger.info("[api] after parse param:"+it)
   json.class.parse.before=groovy:logger.info("[json] before parse class:"+it)
   json.class.parse.after=groovy:logger.info("[json] after parse class:"+it)
   json.method.parse.before=groovy:logger.info("[json] before parse method:"+it)
   json.method.parse.after=groovy:logger.info("[json] after parse method:"+it)
   json.field.parse.before=groovy:logger.info("[json] before parse field:"+it)
   json.field.parse.after=groovy:logger.info("[json] after parse field:"+it)
   ```

2. Console output `easy_api`
   - Please set <kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd> > <kbd> Common</kbd> > <kbd>log</kbd> to `LOW```
   
3. Logs of IDEA: <br>

2023-04-07 13:35:49,097 [  86901]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities to files
2023-04-07 13:35:50,374 [  88178]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities to files
2023-04-07 13:35:52,613 [  90417]   INFO - #com.itangcent.intellij.context.ActionContext - register event [onStart]
2023-04-07 13:35:52,614 [  90418]   INFO - #com.itangcent.intellij.context.ActionContext - cache [is_simple]
2023-04-07 13:35:52,614 [  90418]   INFO - #com.itangcent.intellij.context.ActionContext - cache [is_simple] success
2023-04-07 13:35:52,614 [  90418]   INFO - #com.itangcent.intellij.context.ActionContext - cache [DATA_EVENT_COLLECTOR]
2023-04-07 13:35:52,614 [  90418]   INFO - #com.itangcent.intellij.context.ActionContext - cache [DATA_EVENT_COLLECTOR] success
2023-04-07 13:35:52,614 [  90418]   INFO - #com.itangcent.intellij.context.ActionContext - cache [LOGGER_BUF]
2023-04-07 13:35:52,614 [  90418]   INFO - #com.itangcent.intellij.context.ActionContext - cache [LOGGER_BUF] success
2023-04-07 13:35:52,614 [  90418]   INFO - #com.itangcent.intellij.context.ActionContext - cache [GROOVY_ACTION_EXT_LOADER]
2023-04-07 13:35:52,614 [  90418]   INFO - #com.itangcent.intellij.context.ActionContext - cache [GROOVY_ACTION_EXT_LOADER] success
2023-04-07 13:35:52,615 [  90419]   INFO - #com.itangcent.intellij.context.ActionContext - call event [onStart]
2023-04-07 13:35:52,615 [  90419]   INFO - #com.itangcent.intellij.context.ActionContextMonitor - [[INFO 300]]register ActionContextMonitor of context ActionContext('27e8a2d78c7fbf85')
2023-04-07 13:35:52,615 [  90419]   INFO - #com.itangcent.intellij.context.ActionContext - cache [_monitor_thread]
2023-04-07 13:35:52,615 [  90419]   INFO - #com.itangcent.intellij.context.ActionContext - cache [_monitor_thread] success
2023-04-07 13:35:52,615 [  90419]   INFO - #com.itangcent.intellij.context.ActionContextMonitor - [[INFO 300]]Health check heartbeat ActionContext('27e8a2d78c7fbf85')
2023-04-07 13:35:52,616 [  90420]   INFO - #com.itangcent.intellij.context.ActionContext - register event [onCompleted]
2023-04-07 13:35:52,616 [  90420]   INFO - #com.itangcent.intellij.actions.KotlinAnAction$Companion - [[INFO 300]]start action:com.itangcent.idea.plugin.actions.SuvExportAction
2023-04-07 13:35:52,639 [  90443]   INFO - #com.itangcent.intellij.context.ActionContext - register event [onCompleted]
2023-04-07 13:35:52,641 [  90445]   INFO - #com.itangcent.common.spi.SpiUtils - [[INFO 300]]load services com.itangcent.idea.plugin.Initializer:[com.itangcent.idea.plugin.settings.EnumProcessInitializer@1e81be30]
2023-04-07 13:35:52,642 [  90446]   INFO - #com.itangcent.intellij.context.ActionContext - compute cache [_currentMethod]
2023-04-07 13:35:52,642 [  90446]   INFO - #com.itangcent.intellij.context.ActionContext - compute cache [psi.Element]
2023-04-07 13:35:52,644 [  90448]   INFO - #com.itangcent.intellij.context.ActionContext - compute cache [editor]
2023-04-07 13:35:52,650 [  90454]   INFO - #com.itangcent.intellij.context.ActionContext - cache [logprocess]
2023-04-07 13:35:52,650 [  90454]   INFO - #com.itangcent.intellij.context.ActionContext - cache [logprocess] success
2023-04-07 13:35:52,650 [  90454]   INFO - #com.itangcent.intellij.context.ActionContext - register event [onCompleted]
2023-04-07 13:35:52,651 [  90455]   INFO - #com.itangcent.intellij.logger.ConsoleRunnerLogger - [INFO]	Start find apis...

2023-04-07 13:35:52,653 [  90457]   INFO - #com.itangcent.intellij.context.ActionContext - compute cache [psi.File]
2023-04-07 13:35:52,655 [  90459]   INFO - #com.itangcent.intellij.adaptor.ModuleAdaptor - [[WARN 400]]NoSuchMethod: com.intellij.openapi.project.ProjectUtil.guessModuleDir
2023-04-07 13:35:52,657 [  90461]   INFO - #com.itangcent.intellij.logger.ConsoleRunnerLogger - [TRACE]	find config file:/Users/yanlun/IdeaProjects/spring-demo/cn/.easy.api.config

2023-04-07 13:35:52,657 [  90461]   INFO - #com.itangcent.intellij.config.AbstractConfigReader$Companion - [[INFO 300]]read config file:file:/Users/yanlun/IdeaProjects/spring-demo/cn/.easy.api.config
2023-04-07 13:35:52,658 [  90462]   INFO - #com.itangcent.intellij.config.resource.FileResource$Companion - [[DEBUG 200]]/Users/yanlun/IdeaProjects/spring-demo/cn/.easy.api.config resolved as /Users/yanlun/IdeaProjects/spring-demo/cn/.easy.api.config
2023-04-07 13:35:52,668 [  90472]   INFO - #com.itangcent.common.spi.SpiUtils - [[INFO 300]]load services com.itangcent.common.text.TemplateEvaluatorDecorator:[com.itangcent.common.text.LiteralTemplateEvaluatorDecorator@1133a767, com.itangcent.common.text.GroovyScriptEngineTemplateEvaluatorDecorator@3774037a]
2023-04-07 13:35:52,669 [  90473]   INFO - #com.itangcent.common.spi.SpiUtils - [[INFO 300]]load service com.itangcent.common.text.TemplateEngine:null
2023-04-07 13:35:52,670 [  90474]   INFO - #com.itangcent.common.spi.SpiUtils - [[INFO 300]]load service com.itangcent.intellij.CustomInfo:com.itangcent.idea.plugin.CustomInfoImpl@194d69a5
2023-04-07 13:35:52,675 [  90479]   INFO - #com.itangcent.intellij.logger.ConsoleRunnerLogger - [DEBUG]	use recommend config

2023-04-07 13:35:52,676 [  90480]   INFO - #com.itangcent.intellij.logger.ConsoleRunnerLogger - [DEBUG]	use built-in config

2023-04-07 13:35:52,681 [  90485]   INFO - #com.itangcent.intellij.context.ActionContext - register event [onCompleted]
2023-04-07 13:35:52,753 [  90557]   INFO - #com.itangcent.idea.plugin.api.ClassApiExporterHelper$Companion - [[INFO 300]]wait api parsing... com.itangcent.springbootwebfluxdemo.controller.EntityCtrl
2023-04-07 13:35:52,766 [  90570]   INFO - #com.itangcent.common.spi.SpiUtils - [[INFO 300]]load services com.itangcent.idea.plugin.api.export.core.ClassExporter:[com.itangcent.idea.plugin.api.export.spring.SimpleSpringRequestClassExporter@705d514b, com.itangcent.idea.plugin.api.export.spring.SpringRequestClassExporter@7f195b3a, com.itangcent.idea.plugin.api.export.spring.ActuatorEndpointExporter@5143fc69, com.itangcent.idea.plugin.api.export.yapi.YapiSpringRequestClassExporter@370fa884, com.itangcent.idea.plugin.api.export.feign.FeignRequestClassExporter@2d426027, com.itangcent.idea.plugin.api.export.feign.SimpleFeignRequestClassExporter@18b72e3e, com.itangcent.idea.plugin.api.export.jaxrs.JAXRSRequestClassExporter@56d939f5, com.itangcent.idea.plugin.api.export.jaxrs.SimpleJAXRSRequestClassExporter@1c58e022, com.itangcent.idea.plugin.api.export.generic.GenericMethodDocClassExporter@2225f8d6, com.itangcent.idea.plugin.api.export.generic.GenericRequestClassExporter@342e472, com.itangcent.idea.plugin.api.export.generic.SimpleGenericMethodDocClassExporter@1c4b737e, com.itangcent.idea.plugin.api.export.generic.SimpleGenericRequestClassExporter@47c9c925]
2023-04-07 13:35:52,770 [  90574]   INFO - #com.itangcent.common.spi.SpiUtils - [[INFO 300]]load services com.itangcent.condition.Condition:[com.itangcent.idea.condition.OnClassCondition@594ffc47, com.itangcent.idea.condition.OnMissingClassCondition@18bd5e7c, com.itangcent.idea.plugin.api.export.condition.OnChannelCondition@7f4b20c5, com.itangcent.idea.plugin.api.export.condition.OnDocCondition@253b2c09, com.itangcent.idea.plugin.api.export.condition.OnSimpleCondition@3b0412d, com.itangcent.idea.plugin.condition.OnSettingCondition@710cb199]
2023-04-07 13:35:52,804 [  90608]   INFO - #com.itangcent.spi.SpiCompositeLoader - matched class com.itangcent.idea.plugin.api.export.core.ClassExporter:[class com.itangcent.idea.plugin.api.export.spring.SimpleSpringRequestClassExporter]
2023-04-07 13:35:52,819 [  90623]   INFO - #com.itangcent.intellij.logger.ConsoleRunnerLogger - [INFO]	search api from: com.itangcent.springbootwebfluxdemo.controller.EntityCtrl

2023-04-07 13:35:52,822 [  90626]   INFO - #com.itangcent.common.spi.SpiUtils - [[INFO 300]]load services com.itangcent.idea.plugin.api.export.spring.SpringRequestMappingResolver:[com.itangcent.idea.plugin.api.export.spring.StandardSpringRequestMappingResolver@896391e, com.itangcent.idea.plugin.api.export.spring.CustomSpringRequestMappingResolver@1e5fcf02, com.itangcent.idea.plugin.api.export.feign.RequestLineRequestMappingResolver@46197530]
2023-04-07 13:35:52,824 [  90628]   INFO - #com.itangcent.spi.SpiCompositeLoader - matched class com.itangcent.idea.plugin.api.export.spring.SpringRequestMappingResolver:[class com.itangcent.idea.plugin.api.export.spring.StandardSpringRequestMappingResolver, class com.itangcent.idea.plugin.api.export.spring.CustomSpringRequestMappingResolver]
2023-04-07 13:35:52,829 [  90633]   INFO - #com.itangcent.intellij.jvm.standard.StandardPsiExpressionResolver$Companion - [[DEBUG 200]]process PsiElement: type:class com.intellij.psi.impl.source.tree.java.PsiLiteralExpressionImpl, text:【"/int"】
2023-04-07 13:35:52,833 [  90637]   INFO - #com.itangcent.intellij.logger.ConsoleRunnerLogger - [DEBUG]	load remote config

2023-04-07 13:35:52,844 [  90648]   INFO - #com.itangcent.intellij.context.ActionContext - register event [onCompleted]
2023-04-07 13:35:52,844 [  90648]   INFO - #com.itangcent.intellij.jvm.standard.StandardPsiExpressionResolver$Companion - [[DEBUG 200]]process PsiExpression: type:class com.intellij.psi.impl.source.tree.java.PsiLiteralExpressionImpl, text:【"/int"】
2023-04-07 13:35:52,846 [  90650]   INFO - #com.itangcent.intellij.jvm.standard.StandardPsiExpressionResolver$Companion - [[DEBUG 200]]process PsiElement: type:class com.intellij.psi.impl.source.tree.java.PsiLiteralExpressionImpl, text:【"/double"】
2023-04-07 13:35:52,846 [  90650]   INFO - #com.itangcent.intellij.jvm.standard.StandardPsiExpressionResolver$Companion - [[DEBUG 200]]process PsiExpression: type:class com.intellij.psi.impl.source.tree.java.PsiLiteralExpressionImpl, text:【"/double"】
2023-04-07 13:35:52,846 [  90650]   INFO - #com.itangcent.idea.plugin.api.ClassApiExporterHelper$Companion - [[INFO 300]]api parse com.itangcent.springbootwebfluxdemo.controller.EntityCtrl completed.
2023-04-07 13:35:52,857 [  90661]   INFO - #com.itangcent.common.spi.SpiUtils - [[INFO 300]]load service com.itangcent.idea.icons.IconLoader:null
2023-04-07 13:35:52,858 [  90662]   INFO - #com.itangcent.idea.icons.EasyIcons - [[ERROR 500]]non icon be found in [Ljava.lang.String;@76f9d5be
2023-04-07 13:35:52,863 [  90667]   INFO - #com.itangcent.idea.icons.EasyIcons - icon of javax.swing.JButton[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.5,border=com.intellij.ide.ui.laf.darcula.ui.DarculaButtonPainter@75937cb8,flags=296,maximumSize=,minimumSize=,preferredSize=,defaultIcon=UrlResolver{ownerClass=null, classLoader=null, overriddenPath='null', url=https://raw.githubusercontent.com/tangcent/easy-yapi/blob/master/assets/close.png, useCacheOnLoad=true},disabledIcon=,disabledSelectedIcon=,margin=com.intellij.util.ui.JBInsets[top=0,left=0,bottom=0,right=0],paintBorder=true,paintFocus=true,pressedIcon=,rolloverEnabled=false,rolloverIcon=,rolloverSelectedIcon=,selectedIcon=,text=,defaultCapable=true] -> UrlResolver{ownerClass=null, classLoader=null, overriddenPath='null', url=https://raw.githubusercontent.com/tangcent/easy-yapi/blob/master/assets/close.png, useCacheOnLoad=true}
2023-04-07 13:35:52,863 [  90667]   INFO - #com.itangcent.idea.icons.EasyIcons - [[ERROR 500]]non icon be found in [Ljava.lang.String;@29c7cf76
2023-04-07 13:35:52,864 [  90668]   INFO - #com.itangcent.idea.icons.EasyIcons - icon of javax.swing.JButton[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.5,border=com.intellij.ide.ui.laf.darcula.ui.DarculaButtonPainter@75937cb8,flags=296,maximumSize=,minimumSize=,preferredSize=,defaultIcon=UrlResolver{ownerClass=null, classLoader=null, overriddenPath='null', url=https://raw.githubusercontent.com/tangcent/easy-yapi/blob/master/assets/ok.png, useCacheOnLoad=true},disabledIcon=,disabledSelectedIcon=,margin=com.intellij.util.ui.JBInsets[top=0,left=0,bottom=0,right=0],paintBorder=true,paintFocus=true,pressedIcon=,rolloverEnabled=false,rolloverIcon=,rolloverSelectedIcon=,selectedIcon=,text=,defaultCapable=true] -> UrlResolver{ownerClass=null, classLoader=null, overriddenPath='null', url=https://raw.githubusercontent.com/tangcent/easy-yapi/blob/master/assets/ok.png, useCacheOnLoad=true}
2023-04-07 13:35:52,866 [  90670]   INFO - #com.itangcent.intellij.context.ActionContext - register event [onCompleted]
2023-04-07 13:35:53,621 [  91425]   INFO - #com.itangcent.intellij.context.ActionContextMonitor - [[INFO 300]]Health check heartbeat ActionContext('27e8a2d78c7fbf85')
2023-04-07 13:35:55,006 [  92810]   INFO - sun.awt.AWTThreading - InvocationEvent has timed out (awaiting 1015 ms). Originated at java.desktop/sun.lwawt.macosx.CAccessibility.getFocusOwner(CAccessibility.java:648)
2023-04-07 13:36:00,006 [  97810]   INFO - sun.awt.AWTThreading - InvocationEvent has timed out (awaiting 1543 ms). Originated at java.desktop/sun.lwawt.macosx.CAccessibility.getFocusOwner(CAccessibility.java:648)
2023-04-07 13:36:00,114 [  97918]   INFO - STDERR - com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
2023-04-07 13:36:00,114 [  97918]   INFO - STDERR - 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:397)
2023-04-07 13:36:00,114 [  97918]   INFO - STDERR - 	at com.google.gson.Gson.fromJson(Gson.java:1227)
2023-04-07 13:36:00,114 [  97918]   INFO - STDERR - 	at com.google.gson.Gson.fromJson(Gson.java:1137)
2023-04-07 13:36:00,114 [  97918]   INFO - STDERR - 	at com.google.gson.Gson.fromJson(Gson.java:1047)
2023-04-07 13:36:00,114 [  97918]   INFO - STDERR - 	at com.google.gson.Gson.fromJson(Gson.java:982)
2023-04-07 13:36:00,114 [  97918]   INFO - STDERR - 	at handler.TianTianFundHandler.lambda$stepAction$0(TianTianFundHandler.java:68)
2023-04-07 13:36:00,114 [  97918]   INFO - STDERR - 	at java.base/java.lang.Thread.run(Thread.java:833)
2023-04-07 13:36:00,115 [  97919]   INFO - STDERR - Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
2023-04-07 13:36:00,115 [  97919]   INFO - STDERR - 	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:393)
2023-04-07 13:36:00,115 [  97919]   INFO - STDERR - 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:386)
2023-04-07 13:36:00,115 [  97919]   INFO - STDERR - 	... 6 more
2023-04-07 13:36:02,007 [  99811]   INFO - sun.awt.AWTThreading - InvocationEvent has timed out (awaiting 1998 ms). Originated at java.desktop/sun.lwawt.macosx.CAccessibility.getFocusOwner(CAccessibility.java:648)
2023-04-07 13:36:04,008 [ 101812]   INFO - sun.awt.AWTThreading - InvocationEvent has timed out (awaiting 1933 ms). Originated at java.desktop/sun.lwawt.macosx.CAccessibility.getFocusOwner(CAccessibility.java:648)
2023-04-07 13:36:06,003 [ 103807]   INFO - sun.awt.AWTThreading - InvocationEvent has timed out (awaiting 1980 ms). Originated at java.desktop/sun.lwawt.macosx.CAccessibility.getFocusOwner(CAccessibility.java:648)
2023-04-07 13:36:08,009 [ 105813]   INFO - sun.awt.AWTThreading - InvocationEvent has timed out (awaiting 2004 ms). Originated at java.desktop/sun.lwawt.macosx.CAccessibility.getFocusOwner(CAccessibility.java:648)

**Environment (please complete the following information):**
 - OS: [e.g. mac]
 - IDEA version [IntelliJ IDEA 2023.1 (Ultimate Edition)]
 - Plugin version [2.5.5.212.0]
 - Yapi version [版本: 1.10.2]

**Demo Code**

**CheckList**

   - [x] <kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd> > <kbd> Intelligent</kbd> > <kbd>enable infer</kbd>

**Additional context**

**Comment by yanye666** [comment]
non icon be found in

**Comment by yanye666** [comment]
2023-04-07 17:36:51,748 [ 313166]   INFO - #com.itangcent.idea.icons.EasyIcons - [[ERROR 500]]non icon be found in [Ljava.lang.String;@49d5b1ca
2023-04-07 17:36:51,748 [ 313166]   INFO - #com.itangcent.idea.icons.EasyIcons - icon of javax.swing.JButton[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.5,border=com.intellij.ide.ui.laf.darcula.ui.DarculaButtonPainter@78a37cbb,flags=296,maximumSize=,minimumSize=,preferredSize=,defaultIcon=UrlResolver{ownerClass=null, classLoader=null, overriddenPath='null', url=https://raw.githubusercontent.com/tangcent/easy-yapi/blob/master/assets/ok.png,

**Comment by tangcent** [comment]
> 2023-04-07 17:36:51,748 [ 313166] INFO - #com.itangcent.idea.icons.EasyIcons - [[ERROR 500]]non icon be found in [Ljava.lang.String;@49d5b1ca 2023-04-07 17:36:51,748 [ 313166] INFO - #com.itangcent.idea.icons.EasyIcons - icon of javax.swing.JButton[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.5,border=com.intellij.ide.ui.laf.darcula.ui.DarculaButtonPainter@78a37cbb,flags=296,maximumSize=,minimumSize=,preferredSize=,defaultIcon=UrlResolver{ownerClass=null, classLoader=null, overriddenPath='null', url=https://raw.githubusercontent.com/tangcent/easy-yapi/blob/master/assets/ok.png,
> 
> 看源码，貌似是，[https://raw.githubusercontent.com/tangcent/easy-yapi/blob/master/assets/close.png这两个地址404导致？](https://raw.githubusercontent.com/tangcent/easy-yapi/blob/master/assets/close.png%E8%BF%99%E4%B8%A4%E4%B8%AA%E5%9C%B0%E5%9D%80404%E5%AF%BC%E8%87%B4%EF%BC%9F)

有可能

**Comment by tangcent** [comment]
试试: [easy-yapi-2.5.5.212.0.zip](https://github.com/tangcent/easy-yapi/files/11182396/easy-yapi-2.5.5.212.0.zip)

**Comment by yanye666** [comment]
可以了，感谢支持
