### ISSUE TITLE
[Bug] idea2023插件报错，请问如何处理？以前的插件版本2.2.9

### ISSUE THREAD

**Issue by shan165310175** [tangcent/easy-yapi#986]
java.lang.NoSuchFieldException: modifiers
	at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
	at com.itangcent.common.utils.ReflectKitKt.changeClassPropertyValueByName(ReflectKit.kt:70)
	at com.itangcent.common.utils.AnyKitKt.changePropertyValue(AnyKit.kt:23)
	at com.itangcent.intellij.extend.rx.AutoComputer$wrapBeanProperty$1$propertySetter$1.invoke(AutoComputer.kt:447)
	at com.itangcent.intellij.extend.rx.AutoComputer$wrapBeanProperty$1$propertySetter$1.invoke(AutoComputer.kt:23)
	at com.itangcent.intellij.extend.rx.BeanPropertyWrap.set(AutoComputer.kt:1872)

什么版本有修复，请问一下？

![image](https://github.com/tangcent/easy-yapi/assets/4739230/1fd9efaa-3e3e-4e1d-ad4d-a32c482e0f72)

**Comment by tangcent** [comment]
待修复

**Comment by shan165310175** [comment]
> 待修复

经过测试。2.3.1版本没有报错

**Comment by tangcent** [comment]
> 经过测试。2.3.1版本没有报错

嗯，之前做过一些改动，但还有一些地方用到了`modifiers `, 需要都处理掉。
